"""Lossless normalized replay artifacts and deterministic audit helpers.

The scanner's feature and score contracts deliberately remain unchanged in this
module.  It only changes how a completed logical payload is represented on
 disk: immutable JSON subtrees are put in a snapshot-local content-addressed
store and evidence records retain explicit references to those subtrees.

The logical/physical boundary is intentional:

* ``FeatureVector.as_dict()`` and ``ReplayResult.artifact_dict()`` are the
  semantic, expanded contracts;
* ``pit-replay-artifact-normalized-v1`` is a physical layout contract;
* expansion is required to be lossless, including every evidence and audit
  field.  Deduplication is never a permission to drop evidence.
"""

from __future__ import annotations

import base64
import copy
import gzip
import hashlib
import io
import json
import math
import os
import tempfile
import zlib
from collections.abc import Iterable, Mapping, MutableMapping
from datetime import date, datetime
from pathlib import Path
from typing import Any

import pandas as pd

from .contracts import FeatureEvidence, FeatureVector

NORMALIZED_ARTIFACT_LAYOUT_VERSION = "pit-replay-artifact-normalized-v1"
ARTIFACT_LAYOUT_VERSION = NORMALIZED_ARTIFACT_LAYOUT_VERSION
PIT_REPLAY_ARTIFACT_LAYOUT_VERSION = NORMALIZED_ARTIFACT_LAYOUT_VERSION
DIGEST_CONTRACT_VERSION = "pit-replay-digests-v2"

_REF_KEY = "$ref"
_REF_PREFIX = "sha256:"
_COMPRESSED_PREFIX = b"zlib-json-v1:"
_COMPRESSED_ENCODING = "zlib+base64-json-v1"
_EVIDENCE_SEQUENCE_FIELDS = frozenset(
    {"source_datasets", "source_fields", "periods", "availability_dates", "source_versions"}
)
_EVIDENCE_PAYLOAD_FIELDS = ("provenance", "components", "config", "metadata")
_EVIDENCE_REFERENCE_FIELDS = (
    *_EVIDENCE_PAYLOAD_FIELDS,
    "source_datasets",
    "source_fields",
    "periods",
    "availability_dates",
    "source_versions",
)
_VECTOR_PAYLOAD_FIELDS = ("benchmark_metadata", "metadata", "feature_metadata")
# Measured high-reuse financial audit structures.  Other mapping children stay
# inline in their parent node: recursively interning every tiny status/config
# wrapper created thousands of single-use entries per candidate.
_ARTIFACT_AWARE_CAS_KEYS = frozenset(
    {"observations", "source_chain", "provenance", "periods", "source_versions"}
)

# These are runtime/measurement fields, not information available to a
# historical candidate.  Date-bearing audit fields such as ``as_of_date``,
# ``current_period`` and ``availability_dates`` are deliberately not included.
_RUNTIME_KEYS = frozenset(
    {
        "started_at",
        "finished_at",
        "runtime_timestamp",
        "retrieved_at",
        "elapsed_seconds",
        "duration_seconds",
        "run_elapsed_seconds",
        "stocks_per_second",
        "current_rss_bytes",
        "peak_rss_bytes",
        "swap_used_bytes",
        "memory_address",
        "object_id",
        "diagnostic_timing",
        "diagnostics",
        "timing",
    }
)

# ``trend_contract_version`` is present on the trend evidence generated by
# ``features.trend``.  The name fallback also handles small hand-built audit
# fixtures that omit that field.
_TREND_FEATURE_MARKERS = frozenset(
    {
        "revenue_yoy",
        "net_profit_yoy",
        "operating_profit_yoy",
        "revenue_qoq",
        "net_profit_qoq",
        "operating_profit_qoq",
        "gross_margin",
        "operating_margin",
        "net_margin",
        "revenue_ttm",
        "net_profit_ttm",
        "operating_profit_ttm",
        "yoy_acceleration",
        "qoq_acceleration",
        "consecutive_improvement",
        "sign_transition",
        "margin_inflection",
        "ttm_trend",
        "turnaround_state",
        "turnaround_evidence",
    }
)


def _json_safe(value: Any, _memo: dict[int, Any] | None = None) -> Any:
    """Convert common pandas/numpy values to finite JSON-compatible values."""

    memo = _memo if _memo is not None else {}
    if value is None or value is pd.NA or value is pd.NaT:
        return None
    if isinstance(value, (pd.Timestamp, datetime, date)):
        timestamp = pd.Timestamp(value)
        if timestamp.tzinfo is not None:
            timestamp = timestamp.tz_localize(None)
        return timestamp.isoformat()
    if isinstance(value, Mapping):
        object_key = id(value)
        if object_key in memo:
            return memo[object_key]
        result: dict[str, Any] = {}
        memo[object_key] = result
        result.update({str(key): _json_safe(item, memo) for key, item in value.items()})
        return result
    if isinstance(value, (list, tuple)):
        object_key = id(value)
        if object_key in memo:
            return memo[object_key]
        result_list: list[Any] = []
        memo[object_key] = result_list
        result_list.extend(_json_safe(item, memo) for item in value)
        return result_list
    if isinstance(value, (set, frozenset)):
        values = [_json_safe(item, memo) for item in value]
        return sorted(values, key=lambda item: canonical_json_bytes(item))
    if isinstance(value, bool):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    if hasattr(value, "item") and not isinstance(value, (str, bytes)):
        try:
            return _json_safe(value.item(), memo)
        except (TypeError, ValueError, OverflowError):
            pass
    if hasattr(value, "tolist") and not isinstance(value, (str, bytes)):
        try:
            return _json_safe(value.tolist(), memo)
        except (TypeError, ValueError):
            pass
    try:
        missing = pd.isna(value)
        if isinstance(missing, bool) and missing:
            return None
    except (TypeError, ValueError):
        pass
    return value


def _canonical_safe_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def canonical_json_bytes(value: Any) -> bytes:
    """Return the canonical UTF-8 JSON bytes used by every content hash."""

    return _canonical_safe_bytes(_json_safe(value))


def canonical_json(value: Any) -> str:
    return canonical_json_bytes(value).decode("utf-8")


def content_digest(value: Any) -> str:
    """Return a full SHA-256 hex digest over canonical JSON."""

    return hashlib.sha256(canonical_json_bytes(value)).hexdigest()


def content_ref(value: Any) -> str:
    """Return the canonical content-address format used in normalized files."""

    return _REF_PREFIX + content_digest(value)


def _mapping_content_digest(value: Mapping[str, Any]) -> str:
    """Hash a large mapping in bounded memory while preserving JSON ordering."""

    digest = hashlib.sha256()
    digest.update(b"{")
    for index, key in enumerate(sorted(value, key=str)):
        if index:
            digest.update(b",")
        digest.update(_canonical_safe_bytes(str(key)))
        digest.update(b":")
        child = value[key]
        digest.update(
            _physical_store_value_bytes(child)
            if isinstance(child, bytes)
            else canonical_json_bytes(child)
        )
    digest.update(b"}")
    return digest.hexdigest()


def serialized_json_bytes(value: Any) -> bytes:
    """Return deterministic bytes matching the pretty JSON artifact writer."""

    return (
        json.dumps(
            _json_safe(value),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n"
    ).encode("utf-8")


def _is_container(value: Any) -> bool:
    return isinstance(value, (Mapping, list, tuple))


def _store_bytes(value: Any) -> bytes:
    """Encode one node without defeating cross-node stream compression.

    Earlier artifacts compressed every node independently at zlib level 9 and
    then base64 encoded it.  Besides being CPU intensive, that hid repetition
    between neighbouring nodes from the final compressor.  The decoder still
    accepts that legacy representation, but newly built stores retain canonical
    plain JSON bytes and are compressed once by the snapshot writer.
    """

    return _canonical_safe_bytes(value)


def _is_compressed_bytes(value: Any) -> bool:
    return isinstance(value, bytes) and value.startswith(_COMPRESSED_PREFIX)


def _compressed_wrapper(value: bytes) -> dict[str, str]:
    return {
        "encoding": _COMPRESSED_ENCODING,
        "data": value[len(_COMPRESSED_PREFIX) :].decode("ascii"),
    }


def _is_compressed_wrapper(value: Any) -> bool:
    return (
        isinstance(value, Mapping)
        and value.get("encoding") == _COMPRESSED_ENCODING
        and isinstance(value.get("data"), str)
    )


def _decode_store_bytes(value: bytes) -> Any:
    raw = (
        zlib.decompress(base64.b64decode(value[len(_COMPRESSED_PREFIX) :]))
        if _is_compressed_bytes(value)
        else value
    )
    return json.loads(raw.decode("utf-8"))


def _decode_store_value(value: Any) -> Any:
    if _is_compressed_bytes(value):
        return _decode_store_bytes(value)
    if _is_compressed_wrapper(value):
        compressed = _COMPRESSED_PREFIX + value["data"].encode("ascii")
        return _decode_store_bytes(compressed)
    return copy.deepcopy(value)


def _physical_store_value_bytes(value: Any) -> bytes:
    if isinstance(value, bytes):
        return (
            _canonical_safe_bytes(_compressed_wrapper(value))
            if _is_compressed_bytes(value)
            else value
        )
    return canonical_json_bytes(value)


class ContentAddressedStore:
    """Snapshot-local Merkle-style store keyed by logical JSON content.

    Hashes are computed from the original logical subtree.  Store entries may
    contain references to child entries; this makes repeated nested objects
    (for example TrendSummary observations) physically unique as well as
    repeated top-level provenance objects.
    """

    def __init__(self, entries: Mapping[str, Any] | None = None) -> None:
        # Encoded nodes are kept as canonical JSON bytes in memory.  Parsed
        # Python trees multiply the resident set dramatically for a 100-stock
        # stream even when the final JSON is only a few hundred MiB.
        self._entries: dict[str, bytes] = {}
        # This cache is intentionally scoped by normalize_feature_vector;
        # retaining source objects across streamed candidates would defeat the
        # memory benefit of the physical store.
        self._identity_cache: dict[int, tuple[Any, str]] = {}
        # Share JSON-safe conversions across aliased nested provenance within
        # one candidate.  TrendSummary deliberately reuses observations and
        # source chains across component evidence records.
        self._safe_cache: dict[int, Any] = {}
        if entries is not None:
            for key, value in entries.items():
                ref = str(key)
                if not ref.startswith(_REF_PREFIX):
                    raise ValueError(f"invalid content-addressed ref: {ref!r}")
                if isinstance(value, bytes):
                    self._entries[ref] = bytes(value)
                elif _is_compressed_wrapper(value):
                    compressed = _COMPRESSED_PREFIX + value["data"].encode("ascii")
                    self._entries[ref] = compressed
                else:
                    self._entries[ref] = _store_bytes(_json_safe(value))

    @property
    def entries(self) -> dict[str, Any]:
        return {
            key: _decode_store_bytes(value)
            for key, value in sorted(self._entries.items())
        }

    @property
    def physical_entries(self) -> dict[str, Any]:
        """Return JSON-native physical store values for an artifact payload."""

        return {
            key: (
                _compressed_wrapper(value)
                if _is_compressed_bytes(value)
                else _decode_store_bytes(value)
            )
            for key, value in sorted(self._entries.items())
        }

    def entries_view(self) -> Mapping[str, bytes]:
        """Return a sorted shallow view for streaming writers."""

        return {key: self._entries[key] for key in sorted(self._entries)}

    def __len__(self) -> int:
        return len(self._entries)

    def clear_identity_cache(self) -> None:
        self._identity_cache.clear()
        self._safe_cache.clear()

    def _encode_child(self, value: Any) -> Any:
        if _is_container(value):
            return {_REF_KEY: self._intern_safe(value)}
        return value

    def _encode_node(self, value: Any) -> Any:
        if isinstance(value, Mapping):
            return {
                str(key): (
                    self._encode_child(child)
                    if str(key) in _ARTIFACT_AWARE_CAS_KEYS
                    else child
                )
                for key, child in value.items()
            }
        if isinstance(value, (list, tuple)):
            return [self._encode_child(child) for child in value]
        return value

    def _encode_original_node(self, original: Any) -> Any:
        """Convert and Merkle-encode in one traversal."""

        if isinstance(original, Mapping):
            return {
                str(key): (
                    {_REF_KEY: self._intern_original(child)}
                    if _is_container(child) and str(key) in _ARTIFACT_AWARE_CAS_KEYS
                    else _json_safe(child, self._safe_cache)
                )
                for key, child in original.items()
            }
        if isinstance(original, (list, tuple)):
            return [
                (
                    {_REF_KEY: self._intern_original(child)}
                    if _is_container(child)
                    else _json_safe(child, self._safe_cache)
                )
                for child in original
            ]
        return _json_safe(original, self._safe_cache)

    def _intern_original(self, original: Any) -> str:
        if _is_container(original):
            cached = self._identity_cache.get(id(original))
            if cached is not None and cached[0] is original:
                return cached[1]
        encoded = self._encode_original_node(original)
        # Hash the lossless Merkle node, not the repeatedly expanded logical
        # subtree.  Child refs already commit to their complete contents, so
        # this remains content-addressed while avoiding O(depth * bytes).
        canonical = _canonical_safe_bytes(encoded)
        ref = _REF_PREFIX + hashlib.sha256(canonical).hexdigest()
        if ref not in self._entries:
            self._entries[ref] = _store_bytes(encoded)
        if _is_container(original):
            self._identity_cache[id(original)] = (original, ref)
        return ref

    def _intern_safe(self, safe: Any) -> str:
        encoded = self._encode_node(safe)
        canonical = _canonical_safe_bytes(encoded)
        ref = _REF_PREFIX + hashlib.sha256(canonical).hexdigest()
        if ref not in self._entries:
            self._entries[ref] = _store_bytes(encoded)
        return ref

    def intern(self, value: Any) -> str:
        """Intern one logical JSON value and return its full SHA-256 ref."""

        return self._intern_original(value)

    def digest(self) -> str:
        return _mapping_content_digest(self._entries)

    def serialized_size(self) -> int:
        return len(serialized_json_bytes(self.entries))


def _store_argument(
    store: ContentAddressedStore | Mapping[str, Any] | None,
) -> tuple[ContentAddressedStore, MutableMapping[str, Any] | None, bool]:
    if isinstance(store, ContentAddressedStore):
        return store, None, False
    if store is None:
        return ContentAddressedStore(), None, True
    if not isinstance(store, Mapping):
        raise TypeError("store must be a ContentAddressedStore or mapping")
    # A mutable mapping is synchronized after normalization for callers that
    # intentionally supply their own snapshot-local store.
    target = store if isinstance(store, MutableMapping) else None
    return ContentAddressedStore(store), target, False


def _feature_vector_payload(vector: FeatureVector) -> dict[str, Any]:
    """Build the legacy logical shape without deep-copying nested evidence."""

    benchmark = vector.benchmark_metadata
    return {
        "ts_code": vector.ts_code,
        "as_of_date": vector.as_of_date,
        "version": vector.version,
        "comparable_period_contract_version": vector.comparable_period_contract_version,
        "trend_contract_version": vector.trend_contract_version,
        "values": dict(vector.values),
        "evidence": {
            name: evidence.as_dict(deep_copy=False)
            for name, evidence in vector.evidence.items()
        },
        "risk_flags": list(vector.risk_flags),
        "rejected_reasons": list(vector.rejected_reasons),
        "unknown_features": list(vector.unknown_features),
        "feature_contract_versions": dict(vector.feature_contract_versions),
        "expectation_crowding_contract_version": (
            vector.expectation_crowding_contract_version
        ),
        "benchmark_metadata": dict(benchmark),
        "benchmark_id": benchmark.get("benchmark_id"),
        "benchmark_name": benchmark.get("benchmark_name"),
        "benchmark_contract_version": benchmark.get(
            "benchmark_contract_version", benchmark.get("version")
        ),
        "benchmark_source_dataset": benchmark.get("source_dataset"),
        "metadata": dict(vector.metadata),
        "feature_metadata": dict(vector.metadata),
    }


def _payload(value: Any, *, method: str) -> dict[str, Any]:
    if isinstance(value, FeatureVector):
        # Read nested provenance directly.  Normalization only replaces fields
        # on these new top-level dictionaries and never mutates the vector.
        return _feature_vector_payload(value)
    candidate = getattr(value, method, None)
    if callable(candidate):
        result = candidate()
        if not isinstance(result, Mapping):
            raise TypeError(f"{method}() must return a mapping")
        return copy.deepcopy(dict(result))
    if not isinstance(value, Mapping):
        raise TypeError("artifact payload must be a FeatureVector or mapping")
    return copy.deepcopy(dict(value))


def _evidence_payload(value: Any) -> dict[str, Any]:
    if isinstance(value, FeatureEvidence):
        return dict(value.as_dict(deep_copy=False))
    if not isinstance(value, Mapping):
        raise TypeError("feature evidence must be a FeatureEvidence or mapping")
    # Only top-level reference fields are removed below.  A shallow copy
    # preserves shared nested JSON objects long enough for the store to
    # recognize them without retaining those source objects after a streamed
    # candidate is released.
    return dict(value)


def _normalize_evidence(value: Any, store: ContentAddressedStore) -> dict[str, Any]:
    evidence = _evidence_payload(value)
    for field_name in _EVIDENCE_REFERENCE_FIELDS:
        logical = evidence.pop(
            field_name,
            () if field_name in _EVIDENCE_SEQUENCE_FIELDS else {},
        )
        ref_name = f"{field_name}_ref"
        if ref_name in evidence:
            raise ValueError(f"evidence already contains reserved field {ref_name}")
        evidence[ref_name] = store.intern(logical)
    return evidence


def normalize_feature_vector(
    vector: FeatureVector | Mapping[str, Any],
    *,
    store: ContentAddressedStore | Mapping[str, Any] | None = None,
    provenance_store: ContentAddressedStore | Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Normalize one vector while retaining all logical evidence fields.

    A standalone call owns a small local ``provenance_store`` embedded in the
    returned record, making the result immediately expandable.  Snapshot
    callers pass one shared ``ContentAddressedStore`` so all vectors share it.
    ``provenance_store`` is accepted as a descriptive alias for ``store``.
    """

    if store is not None and provenance_store is not None:
        raise TypeError("pass only one of store or provenance_store")
    selected_store = store if store is not None else provenance_store
    builder, target, owns_store = _store_argument(selected_store)
    payload = _payload(vector, method="as_dict")
    evidence = payload.get("evidence", {})
    if not isinstance(evidence, Mapping):
        raise ValueError("feature vector evidence must be a mapping")
    payload["evidence"] = {
        str(name): _normalize_evidence(item, builder)
        for name, item in evidence.items()
    }
    for field_name in _VECTOR_PAYLOAD_FIELDS:
        if field_name not in payload:
            continue
        logical = payload.pop(field_name)
        ref_name = f"{field_name}_ref"
        if ref_name in payload:
            raise ValueError(f"vector already contains reserved field {ref_name}")
        payload[ref_name] = builder.intern(logical)
    builder.clear_identity_cache()
    if target is not None:
        target.clear()
        target.update(builder.entries)
    if owns_store:
        payload["provenance_store"] = builder.physical_entries
    return payload


def _normalize_replay_payload(
    value: Any,
    store: ContentAddressedStore,
) -> dict[str, Any]:
    payload = _payload(value, method="artifact_dict")
    if payload.get("artifact_layout_version") == NORMALIZED_ARTIFACT_LAYOUT_VERSION:
        payload = expand_normalized_replay_artifact(payload)
    existing_store = payload.pop("provenance_store", None)
    if existing_store is not None and not isinstance(existing_store, Mapping):
        raise ValueError("provenance_store must be a mapping")
    vectors = payload.get("vectors", [])
    if not isinstance(vectors, (list, tuple)):
        raise ValueError("replay vectors must be an array")
    payload["vectors"] = [normalize_feature_vector(item, store=store) for item in vectors]
    payload["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    payload["provenance_store"] = store.physical_entries
    return payload


def normalize_replay_artifact(
    artifact: Any,
    *,
    store: ContentAddressedStore | Mapping[str, Any] | None = None,
    provenance_store: ContentAddressedStore | Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Return a normalized physical representation of a replay artifact."""

    if store is not None and provenance_store is not None:
        raise TypeError("pass only one of store or provenance_store")
    selected_store = store if store is not None else provenance_store
    builder, target, _ = _store_argument(selected_store)
    result = _normalize_replay_payload(artifact, builder)
    if target is not None:
        target.clear()
        target.update(builder.entries)
    return result


def normalize_feature_vectors(
    vectors: Iterable[FeatureVector | Mapping[str, Any]],
) -> dict[str, Any]:
    """Normalize a vector collection with one shared snapshot-local store."""

    store = ContentAddressedStore()
    normalized = [normalize_feature_vector(vector, store=store) for vector in vectors]
    return {
        "artifact_layout_version": NORMALIZED_ARTIFACT_LAYOUT_VERSION,
        "vectors": normalized,
        "provenance_store": store.physical_entries,
    }


def normalize_snapshot_payload(snapshot: Mapping[str, Any]) -> dict[str, Any]:
    """Normalize one validation snapshot, keeping its outer audit envelope."""

    if not isinstance(snapshot, Mapping):
        raise TypeError("snapshot must be a mapping")
    payload = copy.deepcopy(dict(snapshot))
    if payload.get("artifact_layout_version") == NORMALIZED_ARTIFACT_LAYOUT_VERSION:
        payload = expand_normalized_snapshot(payload)
    store = ContentAddressedStore()
    replay = payload.get("replay")
    if isinstance(replay, Mapping):
        payload["replay"] = _normalize_replay_payload(replay, store)
    payload["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    return payload


def normalize_artifact(value: Any) -> dict[str, Any]:
    """Friendly dispatcher for replay or validation-snapshot payloads."""

    if isinstance(value, FeatureVector):
        return normalize_feature_vector(value)
    if hasattr(value, "artifact_dict"):
        return normalize_replay_artifact(value)
    if isinstance(value, Mapping) and "replay" in value:
        return normalize_snapshot_payload(value)
    return normalize_replay_artifact(value)


def _is_ref_marker(value: Any) -> bool:
    return (
        isinstance(value, Mapping)
        and set(value) == {_REF_KEY}
        and isinstance(value.get(_REF_KEY), str)
        and value.get(_REF_KEY, "").startswith(_REF_PREFIX)
    )


def _expand_node(
    value: Any,
    store: Mapping[str, Any],
    active: tuple[str, ...] = (),
) -> Any:
    if _is_compressed_wrapper(value):
        compressed = _COMPRESSED_PREFIX + value["data"].encode("ascii")
        return _expand_node(_decode_store_bytes(compressed), store, active)
    if _is_ref_marker(value):
        ref = str(value[_REF_KEY])
        if ref in active:
            raise ValueError(f"cyclic normalized reference: {ref}")
        if ref not in store:
            raise KeyError(f"missing normalized provenance ref: {ref}")
        return _expand_node(store[ref], store, (*active, ref))
    if isinstance(value, Mapping):
        return {str(key): _expand_node(item, store, active) for key, item in value.items()}
    if isinstance(value, list):
        return [_expand_node(item, store, active) for item in value]
    return copy.deepcopy(value)


def _expand_ref(ref: Any, store: Mapping[str, Any]) -> Any:
    if not isinstance(ref, str) or not ref.startswith(_REF_PREFIX):
        raise ValueError(f"invalid normalized reference: {ref!r}")
    if ref not in store:
        raise KeyError(f"missing normalized provenance ref: {ref}")
    return _expand_node(store[ref], store, (ref,))


def _merge_overlay(base: Any, overlay: Any) -> Any:
    if isinstance(base, Mapping) and isinstance(overlay, Mapping):
        merged = copy.deepcopy(dict(base))
        for key, value in overlay.items():
            merged[str(key)] = (
                _merge_overlay(merged[key], value)
                if key in merged
                else copy.deepcopy(value)
            )
        return merged
    return copy.deepcopy(overlay)


def _restore_evidence_sequences(evidence: dict[str, Any]) -> dict[str, Any]:
    for field_name in _EVIDENCE_SEQUENCE_FIELDS:
        if field_name in evidence and isinstance(evidence[field_name], list):
            # FeatureEvidence.as_dict() exposes these tuple-typed contract
            # fields.  Restoring them makes object-level expansion equal to
            # the legacy Python payload, while JSON-level canonical equality
            # remains list based as required by the physical format.
            evidence[field_name] = tuple(evidence[field_name])
    return evidence


def _restore_legacy_tuple_shapes(value: Any, path: str = "") -> Any:
    """Restore tuple-valued fields exposed by existing Python contracts."""

    if isinstance(value, Mapping):
        result: dict[str, Any] = {}
        for key, child in value.items():
            text = str(key)
            child_path = f"{path}.{text}"
            restored = _restore_legacy_tuple_shapes(child, child_path)
            tuple_field = text in {
                "lookbacks",
                "enabled_groups",
                "mandatory_components",
                "included_optional_components",
                "lookback_sessions",
                "lookback",
            }
            marker = "low_attention_v2_evidence"
            remainder = (
                child_path.split(marker, 1)[1].strip(".").split(".")
                if marker in child_path
                else []
            )
            metadata_evidence_field = (
                text in _EVIDENCE_SEQUENCE_FIELDS and len(remainder) == 2
            )
            if (tuple_field or metadata_evidence_field) and isinstance(restored, list):
                restored = tuple(restored)
            result[text] = restored
        return result
    if isinstance(value, list):
        return [_restore_legacy_tuple_shapes(item, f"{path}[]") for item in value]
    return value


def expand_normalized_vector(
    vector: Mapping[str, Any],
    provenance_store: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Expand one normalized vector back to the legacy logical payload."""

    if not isinstance(vector, Mapping):
        raise TypeError("normalized vector must be a mapping")
    payload = copy.deepcopy(dict(vector))
    embedded_store = payload.pop("provenance_store", None)
    store = provenance_store if provenance_store is not None else embedded_store
    if store is None:
        # A legacy vector with no refs does not need a store.
        store = {}
    if not isinstance(store, Mapping):
        raise ValueError("provenance_store must be a mapping")
    payload.pop("artifact_layout_version", None)
    evidence_payload = payload.get("evidence", {})
    if not isinstance(evidence_payload, Mapping):
        raise ValueError("normalized vector evidence must be a mapping")
    expanded_evidence: dict[str, Any] = {}
    for name, raw in evidence_payload.items():
        evidence = _evidence_payload(raw)
        for field_name in _EVIDENCE_REFERENCE_FIELDS:
            ref_name = f"{field_name}_ref"
            if ref_name in evidence:
                logical = _expand_ref(evidence.pop(ref_name), store)
            elif field_name in evidence:
                logical = evidence[field_name]
            else:
                logical = () if field_name in _EVIDENCE_SEQUENCE_FIELDS else {}
            evidence[field_name] = logical
        overlay = evidence.pop("provenance_overlay", None)
        if overlay is not None:
            evidence["provenance"] = _merge_overlay(evidence["provenance"], overlay)
        expanded_evidence[str(name)] = _restore_evidence_sequences(evidence)
    payload["evidence"] = expanded_evidence
    for field_name in _VECTOR_PAYLOAD_FIELDS:
        ref_name = f"{field_name}_ref"
        if ref_name in payload:
            payload[field_name] = _expand_ref(payload.pop(ref_name), store)
    return _restore_legacy_tuple_shapes(payload)


def expand_normalized_replay_artifact(artifact: Mapping[str, Any]) -> dict[str, Any]:
    """Expand a normalized replay artifact without changing its semantics."""

    if not isinstance(artifact, Mapping):
        raise TypeError("normalized replay artifact must be a mapping")
    payload = copy.deepcopy(dict(artifact))
    store = payload.pop("provenance_store", None)
    if store is None:
        store = {}
    if not isinstance(store, Mapping):
        raise ValueError("provenance_store must be a mapping")
    payload.pop("artifact_layout_version", None)
    payload.pop("deterministic_digests", None)
    vectors = payload.get("vectors", [])
    if not isinstance(vectors, (list, tuple)):
        raise ValueError("normalized replay vectors must be an array")
    payload["vectors"] = [expand_normalized_vector(item, store) for item in vectors]
    return payload


def expand_normalized_snapshot(snapshot: Mapping[str, Any]) -> dict[str, Any]:
    """Expand a normalized validation snapshot to its legacy envelope."""

    if not isinstance(snapshot, Mapping):
        raise TypeError("normalized snapshot must be a mapping")
    payload = copy.deepcopy(dict(snapshot))
    payload.pop("artifact_layout_version", None)
    replay = payload.get("replay")
    if isinstance(replay, Mapping):
        payload["replay"] = expand_normalized_replay_artifact(replay)
    elif "vectors" in payload:
        payload = expand_normalized_replay_artifact(payload)
    return payload


def feature_vector_from_payload(payload: Mapping[str, Any]) -> FeatureVector:
    """Rehydrate a logical vector for PIT validation of a normalized payload."""

    if not isinstance(payload, Mapping):
        raise TypeError("feature vector payload must be a mapping")
    evidence: dict[str, FeatureEvidence] = {}
    evidence_field_names = {item.name for item in __import__("dataclasses").fields(FeatureEvidence)}
    for name, raw in payload.get("evidence", {}).items():
        record = _evidence_payload(raw)
        components = dict(record.get("components") or {})
        for key in (
            "start_session",
            "end_session",
            "stock_start",
            "stock_end",
            "benchmark_start",
            "benchmark_end",
            "benchmark_id",
            "stock_return",
            "benchmark_return",
            "excess_return",
        ):
            if key in record:
                components.setdefault(key, record[key])
        kwargs = {
            key: copy.deepcopy(value)
            for key, value in record.items()
            if key in evidence_field_names
        }
        kwargs.setdefault("feature", str(name))
        kwargs.setdefault("value", payload.get("values", {}).get(name))
        for field_name in _EVIDENCE_SEQUENCE_FIELDS:
            if field_name in kwargs and isinstance(kwargs[field_name], list):
                kwargs[field_name] = tuple(kwargs[field_name])
        kwargs["components"] = components
        evidence[str(name)] = FeatureEvidence(**kwargs)
    vector_field_names = {item.name for item in __import__("dataclasses").fields(FeatureVector)}
    kwargs = {
        key: copy.deepcopy(value)
        for key, value in payload.items()
        if key in vector_field_names and key != "evidence"
    }
    kwargs.setdefault("ts_code", str(payload.get("ts_code", "")))
    kwargs.setdefault("as_of_date", str(payload.get("as_of_date", "")))
    kwargs["evidence"] = evidence
    for field_name in ("risk_flags", "rejected_reasons", "unknown_features"):
        if field_name in kwargs and kwargs[field_name] is None:
            kwargs[field_name] = []
    return FeatureVector(**kwargs)


def _semantic_clean(value: Any, *, key: str | None = None) -> Any:
    if key is not None and key.casefold() in _RUNTIME_KEYS:
        return None
    if isinstance(value, Mapping):
        result: dict[str, Any] = {}
        for raw_key, item in value.items():
            text = str(raw_key)
            if text.casefold() in _RUNTIME_KEYS:
                continue
            cleaned = _semantic_clean(item, key=text)
            if cleaned is not _DROP:
                result[text] = cleaned
        return result
    if isinstance(value, (list, tuple)):
        return [_semantic_clean(item) for item in value]
    if isinstance(value, (set, frozenset)):
        return sorted((_semantic_clean(item) for item in value), key=canonical_json_bytes)
    return value


class _Drop:
    pass


_DROP = _Drop()


def semantic_payload(value: Any) -> Any:
    """Return the canonical semantic view with runtime measurements removed."""

    if isinstance(value, FeatureVector):
        value = value.as_dict()
    elif hasattr(value, "as_dict") and callable(value.as_dict):
        value = value.as_dict()
    elif isinstance(value, Mapping):
        if value.get("artifact_layout_version") == NORMALIZED_ARTIFACT_LAYOUT_VERSION:
            value = (
                expand_normalized_snapshot(value)
                if "replay" in value
                else expand_normalized_replay_artifact(value)
                if "vectors" in value
                else value
            )
        elif "evidence" in value and "provenance_store" in value:
            value = expand_normalized_vector(value)
    return _semantic_clean(value)


def semantic_digest(value: Any) -> str:
    return content_digest(semantic_payload(value))


def _frame_records(frame: Any) -> list[dict[str, Any]]:
    if frame is None:
        return []
    if hasattr(frame, "to_dict"):
        return [dict(record) for record in frame.to_dict(orient="records")]
    if isinstance(frame, (list, tuple)):
        return [dict(record) for record in frame]
    return []


def deterministic_replay_digests(
    result: Any,
    *,
    input_manifest: Mapping[str, Any] | None = None,
    candidate_vector_digests: Mapping[str, str] | None = None,
    provenance_store: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Build stable replay digests independent of timing or object identity."""

    # Determinism is intentionally assembled from bounded components.  Do not
    # call ReplayResult.artifact_dict(): a real replay may stream vectors and
    # its expanded logical artifact can be hundreds of GiB transiently.
    result_mapping = result if isinstance(result, Mapping) else {}

    def component(name: str, default: Any) -> Any:
        return getattr(result, name, result_mapping.get(name, default))

    manifest = input_manifest or {}
    vectors = component("vectors", ())
    if candidate_vector_digests is None:
        digest_store = ContentAddressedStore()
        candidate_vector_digests = {}
        for vector in vectors:
            normalized_vector = normalize_feature_vector(vector, store=digest_store)
            candidate_vector_digests[str(vector.ts_code)] = content_digest(normalized_vector)
        if provenance_store is None:
            provenance_store = digest_store.entries_view()
    else:
        candidate_vector_digests = {
            str(code): str(digest) for code, digest in candidate_vector_digests.items()
        }
    scores = component("scores", ())
    score_payload = [score.as_dict() if hasattr(score, "as_dict") else score for score in scores]
    formal = _frame_records(component("ranked", []))
    diagnostic = _frame_records(component("diagnostic_ranked", []))
    if provenance_store is None:
        provenance_store = {}
    return {
        "digest_contract_version": DIGEST_CONTRACT_VERSION,
        "input_manifest_digest": str(manifest.get("manifest_id") or content_digest(manifest)),
        "config_digest": semantic_digest(component("configuration", {})),
        "universe_decision_digest": semantic_digest(
            [
                item.as_dict() if hasattr(item, "as_dict") else item
                for item in component("universe_decisions", ())
            ]
        ),
        "per_candidate_normalized_vector_digest": dict(
            sorted(candidate_vector_digests.items())
        ),
        "score_digest": semantic_digest(score_payload),
        "formal_ranking_digest": semantic_digest(formal),
        "diagnostic_ranking_digest": semantic_digest(diagnostic),
        "warnings_digest": semantic_digest(list(component("warnings", ()))),
        "provenance_store_digest": (
            _mapping_content_digest(provenance_store)
            if isinstance(provenance_store, Mapping)
            else content_digest(provenance_store)
        ),
    }


def _find_subtrees(value: Any, path: str = "$") -> Iterable[tuple[str, Any]]:
    if isinstance(value, Mapping):
        yield path, value
        for key, child in value.items():
            yield from _find_subtrees(child, f"{path}.{key}")
    elif isinstance(value, (list, tuple)):
        yield path, value
        for index, child in enumerate(value):
            yield from _find_subtrees(child, f"{path}[{index}]")


def _subtree_report(payload: Mapping[str, Any], *, top_n: int) -> dict[str, Any]:
    groups: dict[str, dict[str, Any]] = {}
    canonical_by_object: dict[int, bytes] = {}
    occurrence_count = 0
    subtree_bytes = 0

    def visit(value: Any, path: str) -> None:
        nonlocal occurrence_count, subtree_bytes
        if not isinstance(value, (Mapping, list, tuple)):
            return
        object_key = id(value)
        canonical = canonical_by_object.get(object_key)
        if canonical is None:
            canonical = canonical_json_bytes(value)
            canonical_by_object[object_key] = canonical
        digest = hashlib.sha256(canonical).hexdigest()
        one_size = len(canonical)
        group = groups.setdefault(
            digest,
            {
                "path": path,
                "hash": digest,
                "occurrences": 0,
                "one_size": one_size,
                "canonical": canonical,
            },
        )
        if group["canonical"] != canonical:
            raise ValueError(f"subtree hash collision for {digest}")
        group["occurrences"] += 1
        occurrence_count += 1
        subtree_bytes += one_size
        if isinstance(value, Mapping):
            for key, child in value.items():
                visit(child, f"{path}.{key}")
        else:
            for index, child in enumerate(value):
                visit(child, f"{path}[{index}]")

    visit(payload, "$")
    repeated = []
    for group in groups.values():
        occurrences = int(group["occurrences"])
        if occurrences <= 1:
            continue
        repeated.append(
            {
                "path": group["path"],
                "hash": group["hash"],
                "occurrences": occurrences,
                "one_size": int(group["one_size"]),
                "duplicated_size": int((occurrences - 1) * group["one_size"]),
            }
        )
    repeated.sort(key=lambda row: (-row["duplicated_size"], -row["occurrences"], row["path"]))
    unique_bytes = sum(int(group["one_size"]) for group in groups.values())
    ratio = (subtree_bytes - unique_bytes) / subtree_bytes if subtree_bytes else 0.0
    return {
        "subtree_group_count": len(groups),
        "subtree_occurrence_count": occurrence_count,
        "identical_subtree_group_count": len(repeated),
        "identical_subtree_occurrence_count": sum(row["occurrences"] for row in repeated),
        "identical_subtree_total_duplicated_bytes": sum(
            row["duplicated_size"] for row in repeated
        ),
        "unique_subtree_bytes": unique_bytes,
        "subtree_bytes_before_dedup": subtree_bytes,
        "deduplication_theoretical_ratio": ratio,
        "top_duplicated_structures": repeated[:top_n],
    }


def _find_key_values(value: Any, target: str) -> list[Any]:
    found: list[Any] = []
    if isinstance(value, Mapping):
        for key, child in value.items():
            if str(key) == target:
                found.append(child)
            found.extend(_find_key_values(child, target))
    elif isinstance(value, (list, tuple)):
        for child in value:
            found.extend(_find_key_values(child, target))
    return found


def _is_trend_evidence(name: str, evidence: Mapping[str, Any]) -> bool:
    return (
        name in _TREND_FEATURE_MARKERS
        or evidence.get("trend_contract_version") is not None
        or (
            isinstance(evidence.get("provenance"), Mapping)
            and evidence["provenance"].get("trend_contract_version") is not None
        )
    )


def attribute_feature_vector_size(
    vector: FeatureVector | Mapping[str, Any],
    *,
    top_n: int = 20,
) -> dict[str, Any]:
    """Recursively attribute one serialized FeatureVector's JSON bytes."""

    payload = _payload(vector, method="as_dict")
    evidence_payload = payload.get("evidence", {})
    if not isinstance(evidence_payload, Mapping):
        raise ValueError("feature vector evidence must be a mapping")
    evidence_by_feature = {
        str(name): len(canonical_json_bytes(item)) for name, item in evidence_payload.items()
    }
    provenance_by_feature: dict[str, int] = {}
    components_by_feature: dict[str, int] = {}
    metadata_by_feature: dict[str, int] = {}
    trend_provenance = 0
    non_trend_provenance = 0
    for name, raw in evidence_payload.items():
        evidence = _evidence_payload(raw)
        provenance_bytes = len(canonical_json_bytes(evidence.get("provenance", {})))
        provenance_by_feature[str(name)] = provenance_bytes
        components_by_feature[str(name)] = len(canonical_json_bytes(evidence.get("components", {})))
        metadata_by_feature[str(name)] = len(canonical_json_bytes(evidence.get("metadata", {})))
        if _is_trend_evidence(str(name), evidence):
            trend_provenance += provenance_bytes
        else:
            non_trend_provenance += provenance_bytes
    source_chain_bytes = sum(
        len(canonical_json_bytes(item)) for item in _find_key_values(payload, "source_chain")
    )
    observations_bytes = sum(
        len(canonical_json_bytes(item)) for item in _find_key_values(payload, "observations")
    )
    subtree = _subtree_report(payload, top_n=top_n)
    total = len(canonical_json_bytes(payload))
    return {
        "ts_code": payload.get("ts_code"),
        "as_of_date": payload.get("as_of_date"),
        "total_bytes": total,
        "values": len(canonical_json_bytes(payload.get("values", {}))),
        "evidence_total": len(canonical_json_bytes(evidence_payload)),
        "evidence_by_feature": dict(sorted(evidence_by_feature.items())),
        "provenance": sum(provenance_by_feature.values()),
        "provenance_by_feature": dict(sorted(provenance_by_feature.items())),
        "components": sum(components_by_feature.values()),
        "components_by_feature": dict(sorted(components_by_feature.items())),
        "metadata": len(canonical_json_bytes(payload.get("metadata", {})))
        + sum(metadata_by_feature.values()),
        "metadata_by_feature": dict(sorted(metadata_by_feature.items())),
        "source_chain": source_chain_bytes,
        "observations": observations_bytes,
        "trend_provenance": trend_provenance,
        "non_trend_provenance": non_trend_provenance,
        **subtree,
    }


def audit_feature_vectors(
    vectors: Iterable[FeatureVector | Mapping[str, Any]],
    *,
    top_n: int = 20,
) -> dict[str, Any]:
    """Return per-vector and aggregate attribution for a bounded probe."""

    materialized = list(vectors)
    reports = [attribute_feature_vector_size(vector, top_n=top_n) for vector in materialized]
    aggregate_keys = (
        "total_bytes",
        "values",
        "evidence_total",
        "provenance",
        "components",
        "metadata",
        "source_chain",
        "observations",
        "trend_provenance",
        "non_trend_provenance",
        "identical_subtree_total_duplicated_bytes",
        "unique_subtree_bytes",
        "subtree_bytes_before_dedup",
        "identical_subtree_group_count",
        "identical_subtree_occurrence_count",
    )
    aggregate = {key: sum(int(report.get(key, 0)) for report in reports) for key in aggregate_keys}
    totals = [int(report["total_bytes"]) for report in reports]
    repeated = [
        row
        for report in reports
        for row in report.get("top_duplicated_structures", ())
    ]
    repeated.sort(key=lambda row: (-row["duplicated_size"], -row["occurrences"], row["path"]))
    aggregate.update(
        {
            "candidate_count": len(reports),
            "mean_vector_bytes": sum(totals) / len(totals) if totals else 0.0,
            "min_vector_bytes": min(totals) if totals else 0,
            "max_vector_bytes": max(totals) if totals else 0,
            "vector_reports": reports,
            "top_duplicated_structures": repeated[:top_n],
            "deduplication_theoretical_ratio": (
                (
                    aggregate["subtree_bytes_before_dedup"]
                    - aggregate["unique_subtree_bytes"]
                )
                / aggregate["subtree_bytes_before_dedup"]
                if aggregate["subtree_bytes_before_dedup"]
                else 0.0
            ),
            "cross_vector_note": (
                "subtree identity is attributed per vector; shared cross-candidate refs "
                "are measured by the normalized store"
            ),
        }
    )
    return aggregate


_CANDIDATE_ARRAY_KEYS = ("vectors", "scores", "diagnostic_ranked")


def _candidate_array_bytes(payload: Mapping[str, Any], key: str) -> int:
    values = payload.get(key, [])
    if not isinstance(values, (list, tuple)):
        return 0
    return sum(len(serialized_json_bytes(item)) for item in values)


def _bytes_without_candidate_arrays(payload: Mapping[str, Any]) -> int:
    copy_payload = copy.deepcopy(dict(payload))
    for key in _CANDIDATE_ARRAY_KEYS:
        if key in copy_payload:
            copy_payload[key] = []
    return len(serialized_json_bytes(copy_payload))


def size_comparison(
    legacy_payload: Mapping[str, Any],
    normalized_payload: Mapping[str, Any],
    *,
    projected_candidate_count: int | None = None,
) -> dict[str, Any]:
    """Compare physical sizes and project a larger candidate set linearly.

    The projection is deliberately an estimate, not a license to run a full
    replay.  It scales vector records and the observed shared store separately,
    and reports the method so a later real 5,102-candidate measurement can
    replace it.
    """

    legacy = dict(legacy_payload)
    normalized = dict(normalized_payload)
    legacy_vectors = legacy.get("vectors", [])
    normalized_vectors = normalized.get("vectors", [])
    count = len(legacy_vectors) if isinstance(legacy_vectors, (list, tuple)) else 0
    normalized_count = (
        len(normalized_vectors) if isinstance(normalized_vectors, (list, tuple)) else 0
    )
    if count != normalized_count:
        raise ValueError("legacy and normalized vector counts differ")
    legacy_bytes = len(serialized_json_bytes(legacy))
    normalized_bytes = len(serialized_json_bytes(normalized))
    legacy_vector_bytes = sum(len(serialized_json_bytes(item)) for item in legacy_vectors)
    normalized_vector_bytes = sum(
        len(serialized_json_bytes(item)) for item in normalized_vectors
    )
    store = normalized.get("provenance_store", {})
    store_bytes = len(serialized_json_bytes(store))
    legacy_candidate_bytes = sum(
        _candidate_array_bytes(legacy, key) for key in _CANDIDATE_ARRAY_KEYS
    )
    normalized_candidate_bytes = sum(
        _candidate_array_bytes(normalized, key) for key in _CANDIDATE_ARRAY_KEYS
    )
    legacy_per = legacy_candidate_bytes / count if count else 0.0
    normalized_per = normalized_candidate_bytes / count if count else 0.0
    projection_count = projected_candidate_count if projected_candidate_count is not None else count
    base = max(0, _bytes_without_candidate_arrays(normalized) - store_bytes)
    projected_store = store_bytes
    if count and projection_count > count:
        projected_store = int(math.ceil(store_bytes * projection_count / count))
    projected_normalized = int(
        base + normalized_per * projection_count + projected_store
    )
    projected_legacy = int(
        _bytes_without_candidate_arrays(legacy) + legacy_per * projection_count
    )
    return {
        "candidate_count": count,
        "legacy_expanded_bytes": legacy_bytes,
        "legacy_expanded_estimate_bytes": legacy_bytes,
        "normalized_actual_bytes": normalized_bytes,
        "legacy_per_candidate_bytes": legacy_per,
        "normalized_per_candidate_bytes": normalized_per,
        "legacy_vector_per_candidate_bytes": legacy_vector_bytes / count if count else 0.0,
        "normalized_vector_per_candidate_bytes": (
            normalized_vector_bytes / count if count else 0.0
        ),
        "candidate_array_keys_scaled": list(_CANDIDATE_ARRAY_KEYS),
        "shared_provenance_store_bytes": store_bytes,
        "compression_ratio": legacy_bytes / normalized_bytes if normalized_bytes else None,
        "projected_candidate_count": projection_count,
        "projected_legacy_expanded_bytes": projected_legacy,
        "projected_full_snapshot_bytes": projected_normalized,
        "projected_full_snapshot_gib": projected_normalized / 1024**3,
        "projection_method": (
            "fixed normalized non-vector envelope + measured normalized vector bytes/candidate + "
            "linear upper-bound shared-store growth"
        ),
    }


def measure_feature_vector_sizes(
    vectors: Iterable[FeatureVector | Mapping[str, Any]],
    *,
    projected_candidate_count: int | None = None,
) -> dict[str, Any]:
    """Build a shared-store size report for a vector probe."""

    materialized = list(vectors)
    legacy = {"vectors": [_payload(vector, method="as_dict") for vector in materialized]}
    normalized = normalize_feature_vectors(materialized)
    result = size_comparison(
        legacy,
        normalized,
        projected_candidate_count=projected_candidate_count,
    )
    result["shared_provenance_store_digest"] = _mapping_content_digest(
        normalized["provenance_store"]
    )
    result["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    return result


def measure_replay_artifact_sizes(
    result: Any,
    *,
    projected_candidate_count: int | None = None,
) -> dict[str, Any]:
    """Measure one bounded ReplayResult without expanding a full snapshot."""

    legacy = result.artifact_dict() if hasattr(result, "artifact_dict") else dict(result)
    normalized = normalize_replay_artifact(legacy)
    comparison = size_comparison(
        legacy,
        normalized,
        projected_candidate_count=projected_candidate_count,
    )
    comparison["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    comparison["normalized_provenance_store_digest"] = _mapping_content_digest(
        normalized.get("provenance_store", {})
    )
    return comparison


def assert_lossless_expansion(
    legacy: FeatureVector | Mapping[str, Any],
    normalized: Mapping[str, Any] | None = None,
) -> bool:
    """Assert full recursive equality after normalized expansion.

    JSON canonicalization treats Python tuples as their serialized arrays, so
    this gate compares every value rather than a selected list of fields while
    remaining valid for an artifact that has crossed a JSON read/write
    boundary.
    """

    legacy_payload = _payload(legacy, method="as_dict")
    normalized_payload = normalized or normalize_feature_vector(legacy)
    expanded = expand_normalized_vector(normalized_payload)
    if canonical_json_bytes(expanded) != canonical_json_bytes(legacy_payload):
        raise AssertionError("normalized vector expansion is not lossless")
    return True


def validate_normalized_integrity(payload: Mapping[str, Any]) -> tuple[str, ...]:
    """Check that a normalized payload has refs for every physical evidence map."""

    violations: list[str] = []
    replay = payload.get("replay") if isinstance(payload, Mapping) else None
    target = replay if isinstance(replay, Mapping) else payload
    store = target.get("provenance_store", {}) if isinstance(target, Mapping) else {}
    if not isinstance(store, Mapping):
        return ("provenance_store_not_mapping",)
    vectors = target.get("vectors", []) if isinstance(target, Mapping) else []
    if not isinstance(vectors, (list, tuple)):
        return ("vectors_not_array",)
    for position, vector in enumerate(vectors):
        if not isinstance(vector, Mapping):
            violations.append(f"vector_{position}_not_mapping")
            continue
        evidence = vector.get("evidence", {})
        if not isinstance(evidence, Mapping):
            violations.append(f"vector_{position}_evidence_not_mapping")
            continue
        for name, item in evidence.items():
            if not isinstance(item, Mapping):
                violations.append(f"vector_{position}:{name}:evidence_not_mapping")
                continue
            for field_name in _EVIDENCE_REFERENCE_FIELDS:
                ref = item.get(f"{field_name}_ref")
                if not isinstance(ref, str) or ref not in store:
                    violations.append(f"vector_{position}:{name}:missing_{field_name}_ref")
    return tuple(violations)


def write_json_artifact(path: str | Path, payload: Any) -> Path:
    """Atomically write deterministic JSON for normalized artifact callers."""

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            prefix=f".{destination.name}.",
            suffix=".tmp",
            dir=destination.parent,
            delete=False,
        ) as temporary:
            temporary_path = Path(temporary.name)
            temporary.write(serialized_json_bytes(payload))
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_path, destination)
    except BaseException:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
        raise
    return destination


def write_normalized_snapshot_with_streamed_vectors(
    path: str | Path,
    snapshot: Mapping[str, Any],
    spool_path: str | Path,
    provenance_store: Mapping[str, Any],
    *,
    canonical_spool: bool = False,
    gzip_level: int | None = None,
) -> Path:
    """Write a normalized snapshot while reading vectors line-by-line.

    ``canonical_spool`` is reserved for the private spool produced from a
    successful canonical ``json.dumps`` call.  Such records are copied
    verbatim; externally supplied spools retain the fail-closed parse and
    canonicalization path.  ``gzip_level`` enables deterministic whole-stream
    compression (mtime=0 and no original filename).
    """

    payload = copy.deepcopy(dict(snapshot))
    replay = payload.get("replay")
    if not isinstance(replay, Mapping) or "vectors" not in replay:
        raise ValueError("streamed snapshot payload is missing replay.vectors")
    payload["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    replay = dict(replay)
    replay["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    vector_marker = "__ASHARE_NORMALIZED_VECTOR_STREAM__"
    store_marker = "__ASHARE_NORMALIZED_STORE_STREAM__"
    replay["vectors"] = vector_marker
    replay["provenance_store"] = store_marker
    payload["replay"] = replay
    encoded = json.dumps(
        _json_safe(payload),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
        allow_nan=False,
    )
    vector_marker_text = json.dumps(vector_marker, ensure_ascii=False)
    store_marker_text = json.dumps(store_marker, ensure_ascii=False)
    if encoded.count(vector_marker_text) != 1 or encoded.count(store_marker_text) != 1:
        raise ValueError("normalized stream markers are not unique")
    vector_position = encoded.find(vector_marker_text)
    store_position = encoded.find(store_marker_text)
    if vector_position < 0 or store_position < 0:
        raise ValueError("normalized stream marker is missing")
    if vector_position < store_position:
        prefix = encoded[:vector_position]
        middle = encoded[vector_position + len(vector_marker_text) : store_position]
        suffix = encoded[store_position + len(store_marker_text) :]
        store_before_vectors = False
    else:
        prefix = encoded[:store_position]
        middle = encoded[store_position + len(store_marker_text) : vector_position]
        suffix = encoded[vector_position + len(vector_marker_text) :]
        store_before_vectors = True
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            prefix=f".{destination.name}.",
            suffix=".tmp",
            dir=destination.parent,
            delete=False,
        ) as raw_temporary:
            temporary_path = Path(raw_temporary.name)
            compressed = (
                gzip.GzipFile(
                    filename="",
                    mode="wb",
                    compresslevel=gzip_level,
                    fileobj=raw_temporary,
                    mtime=0,
                )
                if gzip_level is not None
                else raw_temporary
            )
            temporary = io.TextIOWrapper(compressed, encoding="utf-8", newline="")

            def write_store(handle: Any) -> None:
                handle.write("{")
                for index, (ref, value) in enumerate(sorted(provenance_store.items())):
                    if index:
                        handle.write(",")
                    handle.write("\n  ")
                    handle.write(json.dumps(str(ref), ensure_ascii=False))
                    handle.write(": ")
                    if isinstance(value, bytes):
                        if _is_compressed_bytes(value):
                            handle.write(
                                json.dumps(
                                    _compressed_wrapper(value),
                                    ensure_ascii=False,
                                    sort_keys=True,
                                    allow_nan=False,
                                )
                            )
                        else:
                            handle.write(value.decode("utf-8"))
                    else:
                        handle.write(
                            json.dumps(
                                _json_safe(value),
                                ensure_ascii=False,
                                indent=2,
                                sort_keys=True,
                                allow_nan=False,
                            )
                        )
                handle.write("\n}")

            if store_before_vectors:
                temporary.write(prefix)
                write_store(temporary)
                temporary.write(middle)
            else:
                temporary.write(prefix)
            temporary.write("[")
            first = True
            with Path(spool_path).open("r", encoding="utf-8") as spool:
                for line in spool:
                    record = line.strip()
                    if not record:
                        continue
                    if canonical_spool:
                        if not record.startswith("{") or not record.endswith("}"):
                            raise ValueError("canonical normalized vector spool is invalid")
                        encoded_record = record
                    else:
                        decoded = json.loads(record)
                        if not isinstance(decoded, Mapping):
                            raise ValueError("normalized vector spool contains a non-object")
                        encoded_record = json.dumps(
                            _json_safe(decoded),
                            ensure_ascii=False,
                            sort_keys=True,
                            separators=(",", ":"),
                            allow_nan=False,
                        )
                    if not first:
                        temporary.write(",")
                    temporary.write("\n")
                    temporary.write(encoded_record)
                    first = False
            temporary.write("\n]")
            if store_before_vectors:
                temporary.write(suffix)
            else:
                temporary.write(middle)
                write_store(temporary)
                temporary.write(suffix)
            temporary.write("\n")
            temporary.flush()
            if gzip_level is not None:
                temporary.detach().close()
            else:
                temporary.detach()
            raw_temporary.flush()
            os.fsync(raw_temporary.fileno())
        os.replace(temporary_path, destination)
    except BaseException:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
        raise
    return destination


__all__ = [
    "NORMALIZED_ARTIFACT_LAYOUT_VERSION",
    "ARTIFACT_LAYOUT_VERSION",
    "PIT_REPLAY_ARTIFACT_LAYOUT_VERSION",
    "DIGEST_CONTRACT_VERSION",
    "ContentAddressedStore",
    "canonical_json",
    "canonical_json_bytes",
    "content_digest",
    "content_ref",
    "serialized_json_bytes",
    "normalize_feature_vector",
    "normalize_feature_vectors",
    "normalize_replay_artifact",
    "normalize_snapshot_payload",
    "normalize_artifact",
    "expand_normalized_vector",
    "expand_normalized_replay_artifact",
    "expand_normalized_snapshot",
    "feature_vector_from_payload",
    "semantic_payload",
    "semantic_digest",
    "deterministic_replay_digests",
    "attribute_feature_vector_size",
    "audit_feature_vectors",
    "size_comparison",
    "measure_feature_vector_sizes",
    "measure_replay_artifact_sizes",
    "assert_lossless_expansion",
    "validate_normalized_integrity",
    "write_json_artifact",
    "write_normalized_snapshot_with_streamed_vectors",
]
