"""Lossless normalized replay artifacts and deterministic audit helpers.

The scanner's feature and score contracts deliberately remain unchanged in this
module.  It only changes how a completed logical payload is represented on
 disk: immutable JSON subtrees are put in a snapshot-local content-addressed
store and evidence records retain explicit references to those subtrees.

The logical/physical boundary is intentional:

* ``FeatureVector.as_dict()`` and ``ReplayResult.artifact_dict()`` are the
  semantic, expanded contracts;
* ``pit-replay-artifact-normalized-v1`` is a physical layout contract;
* expansion is required to be lossless, including every evidence and audit
  field.  Deduplication is never a permission to drop evidence.
"""

from __future__ import annotations

import base64
import copy
import gzip
import hashlib
import heapq
import io
import json
import math
import os
import tempfile
import zlib
from collections.abc import Callable, Iterable, Iterator, Mapping, MutableMapping
from contextlib import ExitStack
from datetime import date, datetime
from pathlib import Path
from typing import Any

import pandas as pd

from .contracts import FeatureEvidence, FeatureVector

NORMALIZED_ARTIFACT_LAYOUT_VERSION = "pit-replay-artifact-normalized-v1"
ARTIFACT_LAYOUT_VERSION = NORMALIZED_ARTIFACT_LAYOUT_VERSION
PIT_REPLAY_ARTIFACT_LAYOUT_VERSION = NORMALIZED_ARTIFACT_LAYOUT_VERSION
DIGEST_CONTRACT_VERSION = "pit-replay-digests-v2"
FINALIZATION_PROBE_INTERVAL_BYTES = 256 * 1024**2

ResourceProbe = Callable[[str], None]

_REF_KEY = "$ref"
_REF_PREFIX = "sha256:"
_COMPRESSED_PREFIX = b"zlib-json-v1:"
_COMPRESSED_ENCODING = "zlib+base64-json-v1"
_EVIDENCE_SEQUENCE_FIELDS = frozenset(
    {"source_datasets", "source_fields", "periods", "availability_dates", "source_versions"}
)
_EVIDENCE_PAYLOAD_FIELDS = ("provenance", "components", "config", "metadata")
_EVIDENCE_REFERENCE_FIELDS = (
    *_EVIDENCE_PAYLOAD_FIELDS,
    "source_datasets",
    "source_fields",
    "periods",
    "availability_dates",
    "source_versions",
)
_VECTOR_PAYLOAD_FIELDS = ("benchmark_metadata", "metadata", "feature_metadata")
# Measured high-reuse financial audit structures.  Other mapping children stay
# inline in their parent node: recursively interning every tiny status/config
# wrapper created thousands of single-use entries per candidate.
_ARTIFACT_AWARE_CAS_KEYS = frozenset(
    {"observations", "source_chain", "provenance", "periods", "source_versions"}
)

# These are runtime/measurement fields, not information available to a
# historical candidate.  Date-bearing audit fields such as ``as_of_date``,
# ``current_period`` and ``availability_dates`` are deliberately not included.
_RUNTIME_KEYS = frozenset(
    {
        "started_at",
        "finished_at",
        "runtime_timestamp",
        "retrieved_at",
        "elapsed_seconds",
        "duration_seconds",
        "run_elapsed_seconds",
        "stocks_per_second",
        "current_rss_bytes",
        "current_pss_bytes",
        "current_private_bytes",
        "current_swap_bytes",
        "peak_rss_bytes",
        "peak_rss_diagnostic_bytes",
        "swap_free_bytes",
        "swap_used_bytes",
        "available_bytes",
        "live_memory_metric",
        "sampled_at_utc",
        "memory_address",
        "object_id",
        "diagnostic_timing",
        "diagnostics",
        "timing",
    }
)

# ``trend_contract_version`` is present on the trend evidence generated by
# ``features.trend``.  The name fallback also handles small hand-built audit
# fixtures that omit that field.
_TREND_FEATURE_MARKERS = frozenset(
    {
        "revenue_yoy",
        "net_profit_yoy",
        "operating_profit_yoy",
        "revenue_qoq",
        "net_profit_qoq",
        "operating_profit_qoq",
        "gross_margin",
        "operating_margin",
        "net_margin",
        "revenue_ttm",
        "net_profit_ttm",
        "operating_profit_ttm",
        "yoy_acceleration",
        "qoq_acceleration",
        "consecutive_improvement",
        "sign_transition",
        "margin_inflection",
        "ttm_trend",
        "turnaround_state",
        "turnaround_evidence",
    }
)


def _json_safe(value: Any, _memo: dict[int, Any] | None = None) -> Any:
    """Convert common pandas/numpy values to finite JSON-compatible values."""

    memo = _memo if _memo is not None else {}
    if value is None or value is pd.NA or value is pd.NaT:
        return None
    if isinstance(value, (pd.Timestamp, datetime, date)):
        timestamp = pd.Timestamp(value)
        if timestamp.tzinfo is not None:
            timestamp = timestamp.tz_localize(None)
        return timestamp.isoformat()
    if isinstance(value, Mapping):
        object_key = id(value)
        if object_key in memo:
            return memo[object_key]
        result: dict[str, Any] = {}
        memo[object_key] = result
        result.update({str(key): _json_safe(item, memo) for key, item in value.items()})
        return result
    if isinstance(value, (list, tuple)):
        object_key = id(value)
        if object_key in memo:
            return memo[object_key]
        result_list: list[Any] = []
        memo[object_key] = result_list
        result_list.extend(_json_safe(item, memo) for item in value)
        return result_list
    if isinstance(value, (set, frozenset)):
        values = [_json_safe(item, memo) for item in value]
        return sorted(values, key=lambda item: canonical_json_bytes(item))
    if isinstance(value, bool):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    if hasattr(value, "item") and not isinstance(value, (str, bytes)):
        try:
            return _json_safe(value.item(), memo)
        except (TypeError, ValueError, OverflowError):
            pass
    if hasattr(value, "tolist") and not isinstance(value, (str, bytes)):
        try:
            return _json_safe(value.tolist(), memo)
        except (TypeError, ValueError):
            pass
    try:
        missing = pd.isna(value)
        if isinstance(missing, bool) and missing:
            return None
    except (TypeError, ValueError):
        pass
    return value


def _canonical_safe_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def canonical_json_bytes(value: Any) -> bytes:
    """Return the canonical UTF-8 JSON bytes used by every content hash."""

    return _canonical_safe_bytes(_json_safe(value))


def canonical_json(value: Any) -> str:
    return canonical_json_bytes(value).decode("utf-8")


def content_digest(value: Any) -> str:
    """Return a full SHA-256 hex digest over canonical JSON."""

    return hashlib.sha256(canonical_json_bytes(value)).hexdigest()


def content_ref(value: Any) -> str:
    """Return the canonical content-address format used in normalized files."""

    return _REF_PREFIX + content_digest(value)


def _mapping_content_digest(value: Mapping[str, Any]) -> str:
    """Hash a large mapping in bounded memory while preserving JSON ordering."""

    digest = hashlib.sha256()
    digest.update(b"{")
    for index, key in enumerate(sorted(value, key=str)):
        if index:
            digest.update(b",")
        digest.update(_canonical_safe_bytes(str(key)))
        digest.update(b":")
        child = value[key]
        digest.update(
            _physical_store_value_bytes(child)
            if isinstance(child, bytes)
            else canonical_json_bytes(child)
        )
    digest.update(b"}")
    return digest.hexdigest()


def serialized_json_bytes(value: Any) -> bytes:
    """Return deterministic bytes matching the pretty JSON artifact writer."""

    return (
        json.dumps(
            _json_safe(value),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n"
    ).encode("utf-8")


def _is_container(value: Any) -> bool:
    return isinstance(value, (Mapping, list, tuple))


def _store_bytes(value: Any) -> bytes:
    """Encode one node without defeating cross-node stream compression.

    Earlier artifacts compressed every node independently at zlib level 9 and
    then base64 encoded it.  Besides being CPU intensive, that hid repetition
    between neighbouring nodes from the final compressor.  The decoder still
    accepts that legacy representation, but newly built stores retain canonical
    plain JSON bytes and are compressed once by the snapshot writer.
    """

    return _canonical_safe_bytes(value)


def _is_compressed_bytes(value: Any) -> bool:
    return isinstance(value, bytes) and value.startswith(_COMPRESSED_PREFIX)


def _compressed_wrapper(value: bytes) -> dict[str, str]:
    return {
        "encoding": _COMPRESSED_ENCODING,
        "data": value[len(_COMPRESSED_PREFIX) :].decode("ascii"),
    }


def _is_compressed_wrapper(value: Any) -> bool:
    return (
        isinstance(value, Mapping)
        and value.get("encoding") == _COMPRESSED_ENCODING
        and isinstance(value.get("data"), str)
    )


def _decode_store_bytes(value: bytes) -> Any:
    raw = (
        zlib.decompress(base64.b64decode(value[len(_COMPRESSED_PREFIX) :]))
        if _is_compressed_bytes(value)
        else value
    )
    return json.loads(raw.decode("utf-8"))


def _decode_store_value(value: Any) -> Any:
    if _is_compressed_bytes(value):
        return _decode_store_bytes(value)
    if _is_compressed_wrapper(value):
        compressed = _COMPRESSED_PREFIX + value["data"].encode("ascii")
        return _decode_store_bytes(compressed)
    return copy.deepcopy(value)


def _physical_store_value_bytes(value: Any) -> bytes:
    if isinstance(value, bytes):
        return (
            _canonical_safe_bytes(_compressed_wrapper(value))
            if _is_compressed_bytes(value)
            else value
        )
    return canonical_json_bytes(value)


class ContentAddressedStore:
    """Snapshot-local Merkle-style store keyed by logical JSON content.

    Hashes are computed from the original logical subtree.  Store entries may
    contain references to child entries; this makes repeated nested objects
    (for example TrendSummary observations) physically unique as well as
    repeated top-level provenance objects.
    """

    def __init__(self, entries: Mapping[str, Any] | None = None) -> None:
        # Encoded nodes are kept as canonical JSON bytes in memory.  Parsed
        # Python trees multiply the resident set dramatically for a 100-stock
        # stream even when the final JSON is only a few hundred MiB.
        self._entries: dict[str, bytes] = {}
        self._physical_bytes = 0
        # This cache is intentionally scoped by normalize_feature_vector;
        # retaining source objects across streamed candidates would defeat the
        # memory benefit of the physical store.
        self._identity_cache: dict[int, tuple[Any, str]] = {}
        # Share JSON-safe conversions across aliased nested provenance within
        # one candidate.  TrendSummary deliberately reuses observations and
        # source chains across component evidence records.
        self._safe_cache: dict[int, Any] = {}
        if entries is not None:
            for key, value in entries.items():
                ref = str(key)
                if not ref.startswith(_REF_PREFIX):
                    raise ValueError(f"invalid content-addressed ref: {ref!r}")
                if isinstance(value, bytes):
                    encoded = bytes(value)
                elif _is_compressed_wrapper(value):
                    encoded = _COMPRESSED_PREFIX + value["data"].encode("ascii")
                else:
                    encoded = _store_bytes(_json_safe(value))
                self._entries[ref] = encoded
                self._physical_bytes += len(encoded)

    @property
    def entries(self) -> dict[str, Any]:
        return {
            key: _decode_store_bytes(value)
            for key, value in sorted(self._entries.items())
        }

    @property
    def physical_entries(self) -> dict[str, Any]:
        """Return JSON-native physical store values for an artifact payload."""

        return {
            key: (
                _compressed_wrapper(value)
                if _is_compressed_bytes(value)
                else _decode_store_bytes(value)
            )
            for key, value in sorted(self._entries.items())
        }

    def iter_entries_sorted(self) -> Iterator[tuple[str, bytes]]:
        """Yield physical entries in ref order without a second dictionary."""

        for key in sorted(self._entries):
            yield key, self._entries[key]

    def entries_view(self) -> Mapping[str, bytes]:
        """Compatibility view for small stores only.

        Production streaming paths use :meth:`iter_entries_sorted`; this
        method intentionally remains a materialising compatibility API.
        """

        return dict(self.iter_entries_sorted())

    @property
    def entry_count(self) -> int:
        return len(self._entries)

    @property
    def physical_byte_count(self) -> int:
        return self._physical_bytes

    def __len__(self) -> int:
        return len(self._entries)

    def clear_identity_cache(self) -> None:
        self._identity_cache.clear()
        self._safe_cache.clear()

    clear_candidate_identity_cache = clear_identity_cache

    def _encode_child(self, value: Any) -> Any:
        if _is_container(value):
            return {_REF_KEY: self._intern_safe(value)}
        return value

    def _encode_node(self, value: Any) -> Any:
        if isinstance(value, Mapping):
            return {
                str(key): (
                    self._encode_child(child)
                    if str(key) in _ARTIFACT_AWARE_CAS_KEYS
                    else child
                )
                for key, child in value.items()
            }
        if isinstance(value, (list, tuple)):
            return [self._encode_child(child) for child in value]
        return value

    def _encode_original_node(self, original: Any) -> Any:
        """Convert and Merkle-encode in one traversal."""

        if isinstance(original, Mapping):
            return {
                str(key): (
                    {_REF_KEY: self._intern_original(child)}
                    if _is_container(child) and str(key) in _ARTIFACT_AWARE_CAS_KEYS
                    else _json_safe(child, self._safe_cache)
                )
                for key, child in original.items()
            }
        if isinstance(original, (list, tuple)):
            return [
                (
                    {_REF_KEY: self._intern_original(child)}
                    if _is_container(child)
                    else _json_safe(child, self._safe_cache)
                )
                for child in original
            ]
        return _json_safe(original, self._safe_cache)

    def _intern_original(self, original: Any) -> str:
        if _is_container(original):
            cached = self._identity_cache.get(id(original))
            if cached is not None and cached[0] is original:
                return cached[1]
        encoded = self._encode_original_node(original)
        # Hash the lossless Merkle node, not the repeatedly expanded logical
        # subtree.  Child refs already commit to their complete contents, so
        # this remains content-addressed while avoiding O(depth * bytes).
        canonical = _canonical_safe_bytes(encoded)
        ref = _REF_PREFIX + hashlib.sha256(canonical).hexdigest()
        if ref not in self._entries:
            stored = _store_bytes(encoded)
            self._entries[ref] = stored
            self._physical_bytes += len(stored)
        if _is_container(original):
            self._identity_cache[id(original)] = (original, ref)
        return ref

    def _intern_safe(self, safe: Any) -> str:
        encoded = self._encode_node(safe)
        canonical = _canonical_safe_bytes(encoded)
        ref = _REF_PREFIX + hashlib.sha256(canonical).hexdigest()
        if ref not in self._entries:
            stored = _store_bytes(encoded)
            self._entries[ref] = stored
            self._physical_bytes += len(stored)
        return ref

    def intern(self, value: Any) -> str:
        """Intern one logical JSON value and return its full SHA-256 ref."""

        return self._intern_original(value)

    def digest(self) -> str:
        return _mapping_content_digest(self._entries)

    def serialized_size(self) -> int:
        return len(serialized_json_bytes(self.entries))


class ChunkedContentAddressedStore(ContentAddressedStore):
    """A bounded-memory CAS with one reusable external-merge finalization.

    Active entries are flushed to sorted private chunks. :meth:`finalize`
    merges those chunks exactly once into an immutable runtime file while it
    computes the logical mapping digest and verifies duplicate refs. All later
    digest and iteration calls reuse that file instead of rebuilding a merge
    tree.
    """

    MERGE_FAN_IN = 32

    def __init__(
        self,
        directory: str | Path | None = None,
        *,
        chunk_entries: int = 100_000,
        max_active_entries: int = 100_000,
        max_active_physical_bytes: int = 64 * 1024 * 1024,
        merge_fan_in: int = MERGE_FAN_IN,
    ) -> None:
        if min(chunk_entries, max_active_entries, max_active_physical_bytes) <= 0:
            raise ValueError("chunk and active safety limits must be positive")
        if not 2 <= merge_fan_in <= 64:
            raise ValueError("merge_fan_in must be between 2 and 64")
        super().__init__()
        # These are physical safety settings, not candidate-count policies.
        self.chunk_entries = int(chunk_entries)
        self.max_active_entries = int(max_active_entries)
        self.max_active_physical_bytes = int(max_active_physical_bytes)
        self.merge_fan_in = int(merge_fan_in)
        self.peak_open_chunk_streams = 0
        self.merge_group_count = 0
        self.merge_pass_count = 0
        self.finalization_count = 0
        self._temporary_merges: list[Path] = []
        self._chunk_dir = Path(directory) if directory is not None else Path(
            tempfile.mkdtemp(prefix="ashare-cas-")
        )
        self._chunk_dir.mkdir(parents=True, exist_ok=True)
        self._chunks: list[Path] = []
        self._chunk_sequence = 0
        self._finalized_path: Path | None = None
        self._finalized_digest: str | None = None
        self._finalized_entry_count: int | None = None
        self._finalized_physical_bytes: int | None = None
        self._finalization_failed = False

    @property
    def chunk_count(self) -> int:
        return len(self._chunks)

    @property
    def finalized_path(self) -> Path | None:
        return self._finalized_path

    @property
    def is_finalized(self) -> bool:
        return self._finalized_path is not None

    def intern(self, value: Any) -> str:
        if self.is_finalized or self._finalization_failed:
            raise RuntimeError("cannot add entries after CAS finalization")
        return super().intern(value)

    def flush_chunk(self, *, force: bool = False) -> Path | None:
        """Persist the active physical chunk; ``force`` documents the boundary."""

        del force
        if self.is_finalized or self._finalization_failed:
            raise RuntimeError("cannot flush entries after CAS finalization")
        if not self._entries:
            return None
        path = self._chunk_dir / f"chunk-{self._chunk_sequence:08d}.cas"
        self._chunk_sequence += 1
        try:
            with path.open("xb") as handle:
                for ref, value in super().iter_entries_sorted():
                    handle.write(
                        ref.encode("ascii") + b"\t" + base64.b64encode(value) + b"\n"
                    )
        except BaseException:
            path.unlink(missing_ok=True)
            raise
        self._chunks.append(path)
        self._entries.clear()
        self._physical_bytes = 0
        self.clear_identity_cache()
        return path

    def flush_chunk_if_needed(self, *, force: bool = False) -> Path | None:
        """Apply physical safety limits; callers explicitly own candidate batches."""

        if (
            force
            or len(self._entries) >= self.chunk_entries
            or len(self._entries) >= self.max_active_entries
            or self._physical_bytes >= self.max_active_physical_bytes
        ):
            return self.flush_chunk()
        return None

    @staticmethod
    def _merge_streams(
        streams: list[Iterator[tuple[str, bytes]]],
    ) -> Iterator[tuple[str, bytes]]:
        heap: list[tuple[str, int, bytes]] = []
        for index, stream in enumerate(streams):
            try:
                ref, value = next(stream)
            except StopIteration:
                continue
            heapq.heappush(heap, (ref, index, value))
        while heap:
            ref, index, value = heapq.heappop(heap)
            same = [(index, value)]
            while heap and heap[0][0] == ref:
                _, other_index, other_value = heapq.heappop(heap)
                same.append((other_index, other_value))
            if any(other_value != value for _, other_value in same):
                raise ValueError(f"conflicting physical bytes for duplicate ref: {ref}")
            yield ref, value
            for stream_index, _ in same:
                try:
                    next_ref, next_value = next(streams[stream_index])
                except StopIteration:
                    continue
                heapq.heappush(heap, (next_ref, stream_index, next_value))

    @staticmethod
    def _chunk_entries_from_handle(handle: Any) -> Iterator[tuple[str, bytes]]:
        for line in handle:
            ref, encoded = line.rstrip(b"\n").split(b"\t", 1)
            yield ref.decode("ascii"), base64.b64decode(encoded)

    def _merge_group(
        self,
        paths: list[Path],
        output: Path,
        *,
        resource_probe: ResourceProbe | None,
        probe_interval_bytes: int,
        final: bool = False,
    ) -> tuple[str | None, int, int]:
        phase = "cas_final_merge" if final else "cas_intermediate_merge_group"
        if resource_probe is not None:
            resource_probe(f"{phase}_start")
        digest = hashlib.sha256() if final else None
        if digest is not None:
            digest.update(b"{")
        entry_count = 0
        physical_bytes = 0
        bytes_since_probe = 0
        output.unlink(missing_ok=True)
        try:
            with ExitStack() as stack:
                handles = [stack.enter_context(path.open("rb")) for path in paths]
                self.peak_open_chunk_streams = max(
                    self.peak_open_chunk_streams, len(handles)
                )
                streams = [self._chunk_entries_from_handle(handle) for handle in handles]
                with output.open("xb") as target:
                    for ref, value in self._merge_streams(streams):
                        line = (
                            ref.encode("ascii")
                            + b"\t"
                            + base64.b64encode(value)
                            + b"\n"
                        )
                        target.write(line)
                        if digest is not None:
                            if entry_count:
                                digest.update(b",")
                            digest.update(_canonical_safe_bytes(ref))
                            digest.update(b":")
                            digest.update(_physical_store_value_bytes(value))
                        entry_count += 1
                        physical_bytes += len(value)
                        bytes_since_probe += len(line)
                        if (
                            resource_probe is not None
                            and bytes_since_probe >= probe_interval_bytes
                        ):
                            resource_probe(f"{phase}_output_interval")
                            bytes_since_probe = 0
                    target.flush()
            if digest is not None:
                digest.update(b"}")
            if resource_probe is not None:
                resource_probe(f"{phase}_complete")
        except BaseException:
            output.unlink(missing_ok=True)
            raise
        self.merge_group_count += 1
        return digest.hexdigest() if digest is not None else None, entry_count, physical_bytes

    def finalize(
        self,
        *,
        resource_probe: ResourceProbe | None = None,
        probe_interval_bytes: int = FINALIZATION_PROBE_INTERVAL_BYTES,
    ) -> Path:
        """Create and cache the sole sorted runtime store and its digest.

        Duplicate refs with equal bytes are deduplicated by the merge. A
        conflicting duplicate fails closed. Intermediate files are removed as
        soon as a complete successor exists; a failed finalization removes all
        partial/intermediate output and leaves cleanup of surviving source
        chunks to :meth:`close`.
        """

        if probe_interval_bytes <= 0:
            raise ValueError("probe_interval_bytes must be positive")
        if self._finalized_path is not None:
            return self._finalized_path
        if self._finalization_failed:
            raise RuntimeError("CAS finalization previously failed")
        self.flush_chunk(force=True)
        paths = list(self._chunks)
        partial = self._chunk_dir / "finalized.cas.partial"
        final_path = self._chunk_dir / "finalized.cas"
        partial.unlink(missing_ok=True)
        final_path.unlink(missing_ok=True)
        level = 0
        try:
            if resource_probe is not None:
                resource_probe("cas_finalize_start")
            while len(paths) > self.merge_fan_in:
                self.merge_pass_count += 1
                next_paths: list[Path] = []
                for group_index, start in enumerate(
                    range(0, len(paths), self.merge_fan_in)
                ):
                    group = paths[start : start + self.merge_fan_in]
                    output = self._chunk_dir / (
                        f"merge-{level:04d}-{group_index:08d}.cas"
                    )
                    self._merge_group(
                        group,
                        output,
                        resource_probe=resource_probe,
                        probe_interval_bytes=probe_interval_bytes,
                    )
                    self._temporary_merges.append(output)
                    next_paths.append(output)
                    # Each completed group is a durable sorted replacement for
                    # its inputs; releasing them bounds temporary disk growth.
                    for path in group:
                        path.unlink(missing_ok=True)
                        if path in self._chunks:
                            self._chunks.remove(path)
                        if path in self._temporary_merges:
                            self._temporary_merges.remove(path)
                paths = next_paths
                level += 1
            self.merge_pass_count += 1
            digest, entry_count, physical_bytes = self._merge_group(
                paths,
                partial,
                resource_probe=resource_probe,
                probe_interval_bytes=probe_interval_bytes,
                final=True,
            )
            assert digest is not None
            if resource_probe is not None:
                # This is deliberately before promotion. A hard resource gate
                # therefore cannot leave a finalized file behind.
                resource_probe("cas_finalized_store_completion")
            os.replace(partial, final_path)
            for path in paths:
                path.unlink(missing_ok=True)
            self._chunks.clear()
            self._temporary_merges.clear()
            self._finalized_path = final_path
            self._finalized_digest = digest
            self._finalized_entry_count = entry_count
            self._finalized_physical_bytes = physical_bytes
            self.finalization_count += 1
            return final_path
        except BaseException:
            partial.unlink(missing_ok=True)
            final_path.unlink(missing_ok=True)
            for path in self._temporary_merges:
                path.unlink(missing_ok=True)
            self._temporary_merges.clear()
            self._finalization_failed = True
            raise

    def iter_entries_sorted(
        self,
        *,
        resource_probe: ResourceProbe | None = None,
        probe_interval_bytes: int = FINALIZATION_PROBE_INTERVAL_BYTES,
    ) -> Iterator[tuple[str, bytes]]:
        """Read the finalized sorted file directly without another merge."""

        if probe_interval_bytes <= 0:
            raise ValueError("probe_interval_bytes must be positive")
        path = self.finalize(
            resource_probe=resource_probe,
            probe_interval_bytes=probe_interval_bytes,
        )
        if resource_probe is not None:
            resource_probe("cas_finalized_store_iteration_start")
        bytes_since_probe = 0
        with path.open("rb") as handle:
            for ref, value in self._chunk_entries_from_handle(handle):
                yield ref, value
                bytes_since_probe += len(value)
                if (
                    resource_probe is not None
                    and bytes_since_probe >= probe_interval_bytes
                ):
                    resource_probe("cas_finalized_store_iteration_interval")
                    bytes_since_probe = 0
        if resource_probe is not None:
            resource_probe("cas_finalized_store_iteration_complete")

    def digest(
        self,
        *,
        resource_probe: ResourceProbe | None = None,
        probe_interval_bytes: int = FINALIZATION_PROBE_INTERVAL_BYTES,
    ) -> str:
        self.finalize(
            resource_probe=resource_probe,
            probe_interval_bytes=probe_interval_bytes,
        )
        assert self._finalized_digest is not None
        return self._finalized_digest

    def __len__(self) -> int:
        return self.entry_count

    @property
    def entry_count(self) -> int:
        self.finalize()
        assert self._finalized_entry_count is not None
        return self._finalized_entry_count

    @property
    def active_entry_count(self) -> int:
        return len(self._entries)

    @property
    def active_physical_byte_count(self) -> int:
        return self._physical_bytes

    @property
    def physical_byte_count(self) -> int:
        self.finalize()
        assert self._finalized_physical_bytes is not None
        return self._finalized_physical_bytes

    def close(self, *, cleanup: bool = True) -> None:
        if cleanup:
            owned_paths = {
                *self._chunks,
                *self._temporary_merges,
                self._chunk_dir / "finalized.cas",
                self._chunk_dir / "finalized.cas.partial",
            }
            for pattern in ("merge-*.cas",):
                owned_paths.update(self._chunk_dir.glob(pattern))
            for path in owned_paths:
                path.unlink(missing_ok=True)
            self._chunks.clear()
            self._temporary_merges.clear()
            try:
                self._chunk_dir.rmdir()
            except OSError:
                pass
        self._entries.clear()
        self._physical_bytes = 0
        self._finalized_path = None
        self._finalized_digest = None
        self._finalized_entry_count = None
        self._finalized_physical_bytes = None
        self._finalization_failed = False
        self.clear_identity_cache()



def _store_argument(
    store: ContentAddressedStore | Mapping[str, Any] | None,
) -> tuple[ContentAddressedStore, MutableMapping[str, Any] | None, bool]:
    if isinstance(store, ContentAddressedStore):
        return store, None, False
    if store is None:
        return ContentAddressedStore(), None, True
    if not isinstance(store, Mapping):
        raise TypeError("store must be a ContentAddressedStore or mapping")
    # A mutable mapping is synchronized after normalization for callers that
    # intentionally supply their own snapshot-local store.
    target = store if isinstance(store, MutableMapping) else None
    return ContentAddressedStore(store), target, False


def _feature_vector_payload(vector: FeatureVector) -> dict[str, Any]:
    """Build the legacy logical shape without deep-copying nested evidence."""

    benchmark = vector.benchmark_metadata
    return {
        "ts_code": vector.ts_code,
        "as_of_date": vector.as_of_date,
        "version": vector.version,
        "comparable_period_contract_version": vector.comparable_period_contract_version,
        "trend_contract_version": vector.trend_contract_version,
        "values": dict(vector.values),
        "evidence": {
            name: evidence.as_dict(deep_copy=False)
            for name, evidence in vector.evidence.items()
        },
        "risk_flags": list(vector.risk_flags),
        "rejected_reasons": list(vector.rejected_reasons),
        "unknown_features": list(vector.unknown_features),
        "feature_contract_versions": dict(vector.feature_contract_versions),
        "expectation_crowding_contract_version": (
            vector.expectation_crowding_contract_version
        ),
        "benchmark_metadata": dict(benchmark),
        "benchmark_id": benchmark.get("benchmark_id"),
        "benchmark_name": benchmark.get("benchmark_name"),
        "benchmark_contract_version": benchmark.get(
            "benchmark_contract_version", benchmark.get("version")
        ),
        "benchmark_source_dataset": benchmark.get("source_dataset"),
        "metadata": dict(vector.metadata),
        "feature_metadata": dict(vector.metadata),
    }


def _payload(value: Any, *, method: str) -> dict[str, Any]:
    if isinstance(value, FeatureVector):
        # Read nested provenance directly.  Normalization only replaces fields
        # on these new top-level dictionaries and never mutates the vector.
        return _feature_vector_payload(value)
    candidate = getattr(value, method, None)
    if callable(candidate):
        result = candidate()
        if not isinstance(result, Mapping):
            raise TypeError(f"{method}() must return a mapping")
        return copy.deepcopy(dict(result))
    if not isinstance(value, Mapping):
        raise TypeError("artifact payload must be a FeatureVector or mapping")
    return copy.deepcopy(dict(value))


def _evidence_payload(value: Any) -> dict[str, Any]:
    if isinstance(value, FeatureEvidence):
        return dict(value.as_dict(deep_copy=False))
    if not isinstance(value, Mapping):
        raise TypeError("feature evidence must be a FeatureEvidence or mapping")
    # Only top-level reference fields are removed below.  A shallow copy
    # preserves shared nested JSON objects long enough for the store to
    # recognize them without retaining those source objects after a streamed
    # candidate is released.
    return dict(value)


def _normalize_evidence(value: Any, store: ContentAddressedStore) -> dict[str, Any]:
    evidence = _evidence_payload(value)
    for field_name in _EVIDENCE_REFERENCE_FIELDS:
        logical = evidence.pop(
            field_name,
            () if field_name in _EVIDENCE_SEQUENCE_FIELDS else {},
        )
        ref_name = f"{field_name}_ref"
        if ref_name in evidence:
            raise ValueError(f"evidence already contains reserved field {ref_name}")
        evidence[ref_name] = store.intern(logical)
    return evidence


def normalize_feature_vector(
    vector: FeatureVector | Mapping[str, Any],
    *,
    store: ContentAddressedStore | Mapping[str, Any] | None = None,
    provenance_store: ContentAddressedStore | Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Normalize one vector while retaining all logical evidence fields.

    A standalone call owns a small local ``provenance_store`` embedded in the
    returned record, making the result immediately expandable.  Snapshot
    callers pass one shared ``ContentAddressedStore`` so all vectors share it.
    ``provenance_store`` is accepted as a descriptive alias for ``store``.
    """

    if store is not None and provenance_store is not None:
        raise TypeError("pass only one of store or provenance_store")
    selected_store = store if store is not None else provenance_store
    builder, target, owns_store = _store_argument(selected_store)
    payload = _payload(vector, method="as_dict")
    evidence = payload.get("evidence", {})
    if not isinstance(evidence, Mapping):
        raise ValueError("feature vector evidence must be a mapping")
    payload["evidence"] = {
        str(name): _normalize_evidence(item, builder)
        for name, item in evidence.items()
    }
    for field_name in _VECTOR_PAYLOAD_FIELDS:
        if field_name not in payload:
            continue
        logical = payload.pop(field_name)
        ref_name = f"{field_name}_ref"
        if ref_name in payload:
            raise ValueError(f"vector already contains reserved field {ref_name}")
        payload[ref_name] = builder.intern(logical)
    builder.clear_identity_cache()
    if target is not None:
        target.clear()
        target.update(builder.entries)
    if owns_store:
        payload["provenance_store"] = builder.physical_entries
    return payload


def _normalize_replay_payload(
    value: Any,
    store: ContentAddressedStore,
) -> dict[str, Any]:
    payload = _payload(value, method="artifact_dict")
    if payload.get("artifact_layout_version") == NORMALIZED_ARTIFACT_LAYOUT_VERSION:
        payload = expand_normalized_replay_artifact(payload)
    existing_store = payload.pop("provenance_store", None)
    if existing_store is not None and not isinstance(existing_store, Mapping):
        raise ValueError("provenance_store must be a mapping")
    vectors = payload.get("vectors", [])
    if not isinstance(vectors, (list, tuple)):
        raise ValueError("replay vectors must be an array")
    payload["vectors"] = [normalize_feature_vector(item, store=store) for item in vectors]
    payload["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    payload["provenance_store"] = store.physical_entries
    return payload


def normalize_replay_artifact(
    artifact: Any,
    *,
    store: ContentAddressedStore | Mapping[str, Any] | None = None,
    provenance_store: ContentAddressedStore | Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Return a normalized physical representation of a replay artifact."""

    if store is not None and provenance_store is not None:
        raise TypeError("pass only one of store or provenance_store")
    selected_store = store if store is not None else provenance_store
    builder, target, _ = _store_argument(selected_store)
    result = _normalize_replay_payload(artifact, builder)
    if target is not None:
        target.clear()
        target.update(builder.entries)
    return result


def normalize_feature_vectors(
    vectors: Iterable[FeatureVector | Mapping[str, Any]],
) -> dict[str, Any]:
    """Normalize a vector collection with one shared snapshot-local store."""

    store = ContentAddressedStore()
    normalized = [normalize_feature_vector(vector, store=store) for vector in vectors]
    return {
        "artifact_layout_version": NORMALIZED_ARTIFACT_LAYOUT_VERSION,
        "vectors": normalized,
        "provenance_store": store.physical_entries,
    }


def normalize_snapshot_payload(snapshot: Mapping[str, Any]) -> dict[str, Any]:
    """Normalize one validation snapshot, keeping its outer audit envelope."""

    if not isinstance(snapshot, Mapping):
        raise TypeError("snapshot must be a mapping")
    payload = copy.deepcopy(dict(snapshot))
    if payload.get("artifact_layout_version") == NORMALIZED_ARTIFACT_LAYOUT_VERSION:
        payload = expand_normalized_snapshot(payload)
    store = ContentAddressedStore()
    replay = payload.get("replay")
    if isinstance(replay, Mapping):
        payload["replay"] = _normalize_replay_payload(replay, store)
    payload["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    return payload


def normalize_artifact(value: Any) -> dict[str, Any]:
    """Friendly dispatcher for replay or validation-snapshot payloads."""

    if isinstance(value, FeatureVector):
        return normalize_feature_vector(value)
    if hasattr(value, "artifact_dict"):
        return normalize_replay_artifact(value)
    if isinstance(value, Mapping) and "replay" in value:
        return normalize_snapshot_payload(value)
    return normalize_replay_artifact(value)


def _is_ref_marker(value: Any) -> bool:
    return (
        isinstance(value, Mapping)
        and set(value) == {_REF_KEY}
        and isinstance(value.get(_REF_KEY), str)
        and value.get(_REF_KEY, "").startswith(_REF_PREFIX)
    )


def _expand_node(
    value: Any,
    store: Mapping[str, Any],
    active: tuple[str, ...] = (),
) -> Any:
    if _is_compressed_wrapper(value):
        compressed = _COMPRESSED_PREFIX + value["data"].encode("ascii")
        return _expand_node(_decode_store_bytes(compressed), store, active)
    if _is_ref_marker(value):
        ref = str(value[_REF_KEY])
        if ref in active:
            raise ValueError(f"cyclic normalized reference: {ref}")
        if ref not in store:
            raise KeyError(f"missing normalized provenance ref: {ref}")
        return _expand_node(store[ref], store, (*active, ref))
    if isinstance(value, Mapping):
        return {str(key): _expand_node(item, store, active) for key, item in value.items()}
    if isinstance(value, list):
        return [_expand_node(item, store, active) for item in value]
    return copy.deepcopy(value)


def _expand_ref(ref: Any, store: Mapping[str, Any]) -> Any:
    if not isinstance(ref, str) or not ref.startswith(_REF_PREFIX):
        raise ValueError(f"invalid normalized reference: {ref!r}")
    if ref not in store:
        raise KeyError(f"missing normalized provenance ref: {ref}")
    return _expand_node(store[ref], store, (ref,))


def _merge_overlay(base: Any, overlay: Any) -> Any:
    if isinstance(base, Mapping) and isinstance(overlay, Mapping):
        merged = copy.deepcopy(dict(base))
        for key, value in overlay.items():
            merged[str(key)] = (
                _merge_overlay(merged[key], value)
                if key in merged
                else copy.deepcopy(value)
            )
        return merged
    return copy.deepcopy(overlay)


def _restore_evidence_sequences(evidence: dict[str, Any]) -> dict[str, Any]:
    for field_name in _EVIDENCE_SEQUENCE_FIELDS:
        if field_name in evidence and isinstance(evidence[field_name], list):
            # FeatureEvidence.as_dict() exposes these tuple-typed contract
            # fields.  Restoring them makes object-level expansion equal to
            # the legacy Python payload, while JSON-level canonical equality
            # remains list based as required by the physical format.
            evidence[field_name] = tuple(evidence[field_name])
    return evidence


def _restore_legacy_tuple_shapes(value: Any, path: str = "") -> Any:
    """Restore tuple-valued fields exposed by existing Python contracts."""

    if isinstance(value, Mapping):
        result: dict[str, Any] = {}
        for key, child in value.items():
            text = str(key)
            child_path = f"{path}.{text}"
            restored = _restore_legacy_tuple_shapes(child, child_path)
            tuple_field = text in {
                "lookbacks",
                "enabled_groups",
                "mandatory_components",
                "included_optional_components",
                "lookback_sessions",
                "lookback",
            }
            marker = "low_attention_v2_evidence"
            remainder = (
                child_path.split(marker, 1)[1].strip(".").split(".")
                if marker in child_path
                else []
            )
            metadata_evidence_field = (
                text in _EVIDENCE_SEQUENCE_FIELDS and len(remainder) == 2
            )
            if (tuple_field or metadata_evidence_field) and isinstance(restored, list):
                restored = tuple(restored)
            result[text] = restored
        return result
    if isinstance(value, list):
        return [_restore_legacy_tuple_shapes(item, f"{path}[]") for item in value]
    return value


def expand_normalized_vector(
    vector: Mapping[str, Any],
    provenance_store: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Expand one normalized vector back to the legacy logical payload."""

    if not isinstance(vector, Mapping):
        raise TypeError("normalized vector must be a mapping")
    payload = copy.deepcopy(dict(vector))
    embedded_store = payload.pop("provenance_store", None)
    store = provenance_store if provenance_store is not None else embedded_store
    if store is None:
        # A legacy vector with no refs does not need a store.
        store = {}
    if not isinstance(store, Mapping):
        raise ValueError("provenance_store must be a mapping")
    payload.pop("artifact_layout_version", None)
    evidence_payload = payload.get("evidence", {})
    if not isinstance(evidence_payload, Mapping):
        raise ValueError("normalized vector evidence must be a mapping")
    expanded_evidence: dict[str, Any] = {}
    for name, raw in evidence_payload.items():
        evidence = _evidence_payload(raw)
        for field_name in _EVIDENCE_REFERENCE_FIELDS:
            ref_name = f"{field_name}_ref"
            if ref_name in evidence:
                logical = _expand_ref(evidence.pop(ref_name), store)
            elif field_name in evidence:
                logical = evidence[field_name]
            else:
                logical = () if field_name in _EVIDENCE_SEQUENCE_FIELDS else {}
            evidence[field_name] = logical
        overlay = evidence.pop("provenance_overlay", None)
        if overlay is not None:
            evidence["provenance"] = _merge_overlay(evidence["provenance"], overlay)
        expanded_evidence[str(name)] = _restore_evidence_sequences(evidence)
    payload["evidence"] = expanded_evidence
    for field_name in _VECTOR_PAYLOAD_FIELDS:
        ref_name = f"{field_name}_ref"
        if ref_name in payload:
            payload[field_name] = _expand_ref(payload.pop(ref_name), store)
    return _restore_legacy_tuple_shapes(payload)


def expand_normalized_replay_artifact(artifact: Mapping[str, Any]) -> dict[str, Any]:
    """Expand a normalized replay artifact without changing its semantics."""

    if not isinstance(artifact, Mapping):
        raise TypeError("normalized replay artifact must be a mapping")
    payload = copy.deepcopy(dict(artifact))
    store = payload.pop("provenance_store", None)
    if store is None:
        store = {}
    if not isinstance(store, Mapping):
        raise ValueError("provenance_store must be a mapping")
    payload.pop("artifact_layout_version", None)
    payload.pop("deterministic_digests", None)
    vectors = payload.get("vectors", [])
    if not isinstance(vectors, (list, tuple)):
        raise ValueError("normalized replay vectors must be an array")
    payload["vectors"] = [expand_normalized_vector(item, store) for item in vectors]
    return payload


def expand_normalized_snapshot(snapshot: Mapping[str, Any]) -> dict[str, Any]:
    """Expand a normalized validation snapshot to its legacy envelope."""

    if not isinstance(snapshot, Mapping):
        raise TypeError("normalized snapshot must be a mapping")
    payload = copy.deepcopy(dict(snapshot))
    payload.pop("artifact_layout_version", None)
    replay = payload.get("replay")
    if isinstance(replay, Mapping):
        payload["replay"] = expand_normalized_replay_artifact(replay)
    elif "vectors" in payload:
        payload = expand_normalized_replay_artifact(payload)
    return payload


def feature_vector_from_payload(payload: Mapping[str, Any]) -> FeatureVector:
    """Rehydrate a logical vector for PIT validation of a normalized payload."""

    if not isinstance(payload, Mapping):
        raise TypeError("feature vector payload must be a mapping")
    evidence: dict[str, FeatureEvidence] = {}
    evidence_field_names = {item.name for item in __import__("dataclasses").fields(FeatureEvidence)}
    for name, raw in payload.get("evidence", {}).items():
        record = _evidence_payload(raw)
        components = dict(record.get("components") or {})
        for key in (
            "start_session",
            "end_session",
            "stock_start",
            "stock_end",
            "benchmark_start",
            "benchmark_end",
            "benchmark_id",
            "stock_return",
            "benchmark_return",
            "excess_return",
        ):
            if key in record:
                components.setdefault(key, record[key])
        kwargs = {
            key: copy.deepcopy(value)
            for key, value in record.items()
            if key in evidence_field_names
        }
        kwargs.setdefault("feature", str(name))
        kwargs.setdefault("value", payload.get("values", {}).get(name))
        for field_name in _EVIDENCE_SEQUENCE_FIELDS:
            if field_name in kwargs and isinstance(kwargs[field_name], list):
                kwargs[field_name] = tuple(kwargs[field_name])
        kwargs["components"] = components
        evidence[str(name)] = FeatureEvidence(**kwargs)
    vector_field_names = {item.name for item in __import__("dataclasses").fields(FeatureVector)}
    kwargs = {
        key: copy.deepcopy(value)
        for key, value in payload.items()
        if key in vector_field_names and key != "evidence"
    }
    kwargs.setdefault("ts_code", str(payload.get("ts_code", "")))
    kwargs.setdefault("as_of_date", str(payload.get("as_of_date", "")))
    kwargs["evidence"] = evidence
    for field_name in ("risk_flags", "rejected_reasons", "unknown_features"):
        if field_name in kwargs and kwargs[field_name] is None:
            kwargs[field_name] = []
    return FeatureVector(**kwargs)


def _semantic_clean(value: Any, *, key: str | None = None) -> Any:
    if key is not None and key.casefold() in _RUNTIME_KEYS:
        return None
    if isinstance(value, Mapping):
        result: dict[str, Any] = {}
        for raw_key, item in value.items():
            text = str(raw_key)
            if text.casefold() in _RUNTIME_KEYS:
                continue
            cleaned = _semantic_clean(item, key=text)
            if cleaned is not _DROP:
                result[text] = cleaned
        return result
    if isinstance(value, (list, tuple)):
        return [_semantic_clean(item) for item in value]
    if isinstance(value, (set, frozenset)):
        return sorted((_semantic_clean(item) for item in value), key=canonical_json_bytes)
    return value


class _Drop:
    pass


_DROP = _Drop()


def semantic_payload(value: Any) -> Any:
    """Return the canonical semantic view with runtime measurements removed."""

    if isinstance(value, FeatureVector):
        value = value.as_dict()
    elif hasattr(value, "as_dict") and callable(value.as_dict):
        value = value.as_dict()
    elif isinstance(value, Mapping):
        if value.get("artifact_layout_version") == NORMALIZED_ARTIFACT_LAYOUT_VERSION:
            value = (
                expand_normalized_snapshot(value)
                if "replay" in value
                else expand_normalized_replay_artifact(value)
                if "vectors" in value
                else value
            )
        elif "evidence" in value and "provenance_store" in value:
            value = expand_normalized_vector(value)
    return _semantic_clean(value)


def semantic_digest(value: Any) -> str:
    return content_digest(semantic_payload(value))


def semantic_sequence_digest(values: Iterable[Any]) -> str:
    """Hash a semantic JSON array with only one expanded item in memory.

    The emitted canonical bytes are exactly those used by
    ``semantic_digest([item1, item2, ...])``: an opening bracket, canonical
    semantic items in iteration order separated by commas, and a closing
    bracket. Objects with ``as_dict()`` are expanded one at a time.
    """

    digest = hashlib.sha256()
    digest.update(b"[")
    for index, value in enumerate(values):
        if index:
            digest.update(b",")
        digest.update(canonical_json_bytes(semantic_payload(value)))
    digest.update(b"]")
    return digest.hexdigest()


def _frame_records(frame: Any) -> list[dict[str, Any]]:
    if frame is None:
        return []
    if hasattr(frame, "to_dict"):
        return [dict(record) for record in frame.to_dict(orient="records")]
    if isinstance(frame, (list, tuple)):
        return [dict(record) for record in frame]
    return []


def deterministic_replay_digests(
    result: Any,
    *,
    input_manifest: Mapping[str, Any] | None = None,
    candidate_vector_digests: Mapping[str, str] | None = None,
    provenance_store: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
) -> dict[str, Any]:
    """Build stable replay digests independent of timing or object identity."""

    # Determinism is intentionally assembled from bounded components.  Do not
    # call ReplayResult.artifact_dict(): a real replay may stream vectors and
    # its expanded logical artifact can be hundreds of GiB transiently.
    result_mapping = result if isinstance(result, Mapping) else {}

    def component(name: str, default: Any) -> Any:
        return getattr(result, name, result_mapping.get(name, default))

    manifest = input_manifest or {}
    vectors = component("vectors", ())
    if candidate_vector_digests is None:
        digest_store = ContentAddressedStore()
        candidate_vector_digests = {}
        for vector in vectors:
            normalized_vector = normalize_feature_vector(vector, store=digest_store)
            candidate_vector_digests[str(vector.ts_code)] = content_digest(normalized_vector)
        if provenance_store is None:
            provenance_store = digest_store.entries_view()
    else:
        candidate_vector_digests = {
            str(code): str(digest) for code, digest in candidate_vector_digests.items()
        }
    scores = component("scores", ())
    formal = _frame_records(component("ranked", []))
    diagnostic = _frame_records(component("diagnostic_ranked", []))
    if provenance_store is None:
        provenance_store = {}
    if provenance_store is not None and hasattr(provenance_store, "digest"):
        provenance_store_digest = provenance_store.digest()
    elif isinstance(provenance_store, Mapping):
        provenance_store_digest = _mapping_content_digest(provenance_store)
    elif provenance_store is None:
        provenance_store_digest = _mapping_content_digest({})
    else:
        # This compatibility path is for small external iterators only.
        digest_store = ContentAddressedStore(dict(provenance_store))
        provenance_store_digest = digest_store.digest()
    return {
        "digest_contract_version": DIGEST_CONTRACT_VERSION,
        "input_manifest_digest": str(manifest.get("manifest_id") or content_digest(manifest)),
        "config_digest": semantic_digest(component("configuration", {})),
        "universe_decision_digest": semantic_sequence_digest(
            component("universe_decisions", ())
        ),
        "per_candidate_normalized_vector_digest": dict(
            sorted(candidate_vector_digests.items())
        ),
        "score_digest": semantic_sequence_digest(scores),
        "formal_ranking_digest": semantic_digest(formal),
        "diagnostic_ranking_digest": semantic_digest(diagnostic),
        "warnings_digest": semantic_digest(list(component("warnings", ()))),
        "provenance_store_digest": provenance_store_digest,
    }


def _find_subtrees(value: Any, path: str = "$") -> Iterable[tuple[str, Any]]:
    if isinstance(value, Mapping):
        yield path, value
        for key, child in value.items():
            yield from _find_subtrees(child, f"{path}.{key}")
    elif isinstance(value, (list, tuple)):
        yield path, value
        for index, child in enumerate(value):
            yield from _find_subtrees(child, f"{path}[{index}]")


def _subtree_report(payload: Mapping[str, Any], *, top_n: int) -> dict[str, Any]:
    groups: dict[str, dict[str, Any]] = {}
    canonical_by_object: dict[int, bytes] = {}
    occurrence_count = 0
    subtree_bytes = 0

    def visit(value: Any, path: str) -> None:
        nonlocal occurrence_count, subtree_bytes
        if not isinstance(value, (Mapping, list, tuple)):
            return
        object_key = id(value)
        canonical = canonical_by_object.get(object_key)
        if canonical is None:
            canonical = canonical_json_bytes(value)
            canonical_by_object[object_key] = canonical
        digest = hashlib.sha256(canonical).hexdigest()
        one_size = len(canonical)
        group = groups.setdefault(
            digest,
            {
                "path": path,
                "hash": digest,
                "occurrences": 0,
                "one_size": one_size,
                "canonical": canonical,
            },
        )
        if group["canonical"] != canonical:
            raise ValueError(f"subtree hash collision for {digest}")
        group["occurrences"] += 1
        occurrence_count += 1
        subtree_bytes += one_size
        if isinstance(value, Mapping):
            for key, child in value.items():
                visit(child, f"{path}.{key}")
        else:
            for index, child in enumerate(value):
                visit(child, f"{path}[{index}]")

    visit(payload, "$")
    repeated = []
    for group in groups.values():
        occurrences = int(group["occurrences"])
        if occurrences <= 1:
            continue
        repeated.append(
            {
                "path": group["path"],
                "hash": group["hash"],
                "occurrences": occurrences,
                "one_size": int(group["one_size"]),
                "duplicated_size": int((occurrences - 1) * group["one_size"]),
            }
        )
    repeated.sort(key=lambda row: (-row["duplicated_size"], -row["occurrences"], row["path"]))
    unique_bytes = sum(int(group["one_size"]) for group in groups.values())
    ratio = (subtree_bytes - unique_bytes) / subtree_bytes if subtree_bytes else 0.0
    return {
        "subtree_group_count": len(groups),
        "subtree_occurrence_count": occurrence_count,
        "identical_subtree_group_count": len(repeated),
        "identical_subtree_occurrence_count": sum(row["occurrences"] for row in repeated),
        "identical_subtree_total_duplicated_bytes": sum(
            row["duplicated_size"] for row in repeated
        ),
        "unique_subtree_bytes": unique_bytes,
        "subtree_bytes_before_dedup": subtree_bytes,
        "deduplication_theoretical_ratio": ratio,
        "top_duplicated_structures": repeated[:top_n],
    }


def _find_key_values(value: Any, target: str) -> list[Any]:
    found: list[Any] = []
    if isinstance(value, Mapping):
        for key, child in value.items():
            if str(key) == target:
                found.append(child)
            found.extend(_find_key_values(child, target))
    elif isinstance(value, (list, tuple)):
        for child in value:
            found.extend(_find_key_values(child, target))
    return found


def _is_trend_evidence(name: str, evidence: Mapping[str, Any]) -> bool:
    return (
        name in _TREND_FEATURE_MARKERS
        or evidence.get("trend_contract_version") is not None
        or (
            isinstance(evidence.get("provenance"), Mapping)
            and evidence["provenance"].get("trend_contract_version") is not None
        )
    )


def attribute_feature_vector_size(
    vector: FeatureVector | Mapping[str, Any],
    *,
    top_n: int = 20,
) -> dict[str, Any]:
    """Recursively attribute one serialized FeatureVector's JSON bytes."""

    payload = _payload(vector, method="as_dict")
    evidence_payload = payload.get("evidence", {})
    if not isinstance(evidence_payload, Mapping):
        raise ValueError("feature vector evidence must be a mapping")
    evidence_by_feature = {
        str(name): len(canonical_json_bytes(item)) for name, item in evidence_payload.items()
    }
    provenance_by_feature: dict[str, int] = {}
    components_by_feature: dict[str, int] = {}
    metadata_by_feature: dict[str, int] = {}
    trend_provenance = 0
    non_trend_provenance = 0
    for name, raw in evidence_payload.items():
        evidence = _evidence_payload(raw)
        provenance_bytes = len(canonical_json_bytes(evidence.get("provenance", {})))
        provenance_by_feature[str(name)] = provenance_bytes
        components_by_feature[str(name)] = len(canonical_json_bytes(evidence.get("components", {})))
        metadata_by_feature[str(name)] = len(canonical_json_bytes(evidence.get("metadata", {})))
        if _is_trend_evidence(str(name), evidence):
            trend_provenance += provenance_bytes
        else:
            non_trend_provenance += provenance_bytes
    source_chain_bytes = sum(
        len(canonical_json_bytes(item)) for item in _find_key_values(payload, "source_chain")
    )
    observations_bytes = sum(
        len(canonical_json_bytes(item)) for item in _find_key_values(payload, "observations")
    )
    subtree = _subtree_report(payload, top_n=top_n)
    total = len(canonical_json_bytes(payload))
    return {
        "ts_code": payload.get("ts_code"),
        "as_of_date": payload.get("as_of_date"),
        "total_bytes": total,
        "values": len(canonical_json_bytes(payload.get("values", {}))),
        "evidence_total": len(canonical_json_bytes(evidence_payload)),
        "evidence_by_feature": dict(sorted(evidence_by_feature.items())),
        "provenance": sum(provenance_by_feature.values()),
        "provenance_by_feature": dict(sorted(provenance_by_feature.items())),
        "components": sum(components_by_feature.values()),
        "components_by_feature": dict(sorted(components_by_feature.items())),
        "metadata": len(canonical_json_bytes(payload.get("metadata", {})))
        + sum(metadata_by_feature.values()),
        "metadata_by_feature": dict(sorted(metadata_by_feature.items())),
        "source_chain": source_chain_bytes,
        "observations": observations_bytes,
        "trend_provenance": trend_provenance,
        "non_trend_provenance": non_trend_provenance,
        **subtree,
    }


def audit_feature_vectors(
    vectors: Iterable[FeatureVector | Mapping[str, Any]],
    *,
    top_n: int = 20,
) -> dict[str, Any]:
    """Return per-vector and aggregate attribution for a bounded probe."""

    materialized = list(vectors)
    reports = [attribute_feature_vector_size(vector, top_n=top_n) for vector in materialized]
    aggregate_keys = (
        "total_bytes",
        "values",
        "evidence_total",
        "provenance",
        "components",
        "metadata",
        "source_chain",
        "observations",
        "trend_provenance",
        "non_trend_provenance",
        "identical_subtree_total_duplicated_bytes",
        "unique_subtree_bytes",
        "subtree_bytes_before_dedup",
        "identical_subtree_group_count",
        "identical_subtree_occurrence_count",
    )
    aggregate = {key: sum(int(report.get(key, 0)) for report in reports) for key in aggregate_keys}
    totals = [int(report["total_bytes"]) for report in reports]
    repeated = [
        row
        for report in reports
        for row in report.get("top_duplicated_structures", ())
    ]
    repeated.sort(key=lambda row: (-row["duplicated_size"], -row["occurrences"], row["path"]))
    aggregate.update(
        {
            "candidate_count": len(reports),
            "mean_vector_bytes": sum(totals) / len(totals) if totals else 0.0,
            "min_vector_bytes": min(totals) if totals else 0,
            "max_vector_bytes": max(totals) if totals else 0,
            "vector_reports": reports,
            "top_duplicated_structures": repeated[:top_n],
            "deduplication_theoretical_ratio": (
                (
                    aggregate["subtree_bytes_before_dedup"]
                    - aggregate["unique_subtree_bytes"]
                )
                / aggregate["subtree_bytes_before_dedup"]
                if aggregate["subtree_bytes_before_dedup"]
                else 0.0
            ),
            "cross_vector_note": (
                "subtree identity is attributed per vector; shared cross-candidate refs "
                "are measured by the normalized store"
            ),
        }
    )
    return aggregate


_CANDIDATE_ARRAY_KEYS = ("vectors", "scores", "diagnostic_ranked")


def _candidate_array_bytes(payload: Mapping[str, Any], key: str) -> int:
    values = payload.get(key, [])
    if not isinstance(values, (list, tuple)):
        return 0
    return sum(len(serialized_json_bytes(item)) for item in values)


def _bytes_without_candidate_arrays(payload: Mapping[str, Any]) -> int:
    copy_payload = copy.deepcopy(dict(payload))
    for key in _CANDIDATE_ARRAY_KEYS:
        if key in copy_payload:
            copy_payload[key] = []
    return len(serialized_json_bytes(copy_payload))


def size_comparison(
    legacy_payload: Mapping[str, Any],
    normalized_payload: Mapping[str, Any],
    *,
    projected_candidate_count: int | None = None,
) -> dict[str, Any]:
    """Compare physical sizes and project a larger candidate set linearly.

    The projection is deliberately an estimate, not a license to run a full
    replay.  It scales vector records and the observed shared store separately,
    and reports the method so a later real 5,102-candidate measurement can
    replace it.
    """

    legacy = dict(legacy_payload)
    normalized = dict(normalized_payload)
    legacy_vectors = legacy.get("vectors", [])
    normalized_vectors = normalized.get("vectors", [])
    count = len(legacy_vectors) if isinstance(legacy_vectors, (list, tuple)) else 0
    normalized_count = (
        len(normalized_vectors) if isinstance(normalized_vectors, (list, tuple)) else 0
    )
    if count != normalized_count:
        raise ValueError("legacy and normalized vector counts differ")
    legacy_bytes = len(serialized_json_bytes(legacy))
    normalized_bytes = len(serialized_json_bytes(normalized))
    legacy_vector_bytes = sum(len(serialized_json_bytes(item)) for item in legacy_vectors)
    normalized_vector_bytes = sum(
        len(serialized_json_bytes(item)) for item in normalized_vectors
    )
    store = normalized.get("provenance_store", {})
    store_bytes = len(serialized_json_bytes(store))
    legacy_candidate_bytes = sum(
        _candidate_array_bytes(legacy, key) for key in _CANDIDATE_ARRAY_KEYS
    )
    normalized_candidate_bytes = sum(
        _candidate_array_bytes(normalized, key) for key in _CANDIDATE_ARRAY_KEYS
    )
    legacy_per = legacy_candidate_bytes / count if count else 0.0
    normalized_per = normalized_candidate_bytes / count if count else 0.0
    projection_count = projected_candidate_count if projected_candidate_count is not None else count
    base = max(0, _bytes_without_candidate_arrays(normalized) - store_bytes)
    projected_store = store_bytes
    if count and projection_count > count:
        projected_store = int(math.ceil(store_bytes * projection_count / count))
    projected_normalized = int(
        base + normalized_per * projection_count + projected_store
    )
    projected_legacy = int(
        _bytes_without_candidate_arrays(legacy) + legacy_per * projection_count
    )
    return {
        "candidate_count": count,
        "legacy_expanded_bytes": legacy_bytes,
        "legacy_expanded_estimate_bytes": legacy_bytes,
        "normalized_actual_bytes": normalized_bytes,
        "legacy_per_candidate_bytes": legacy_per,
        "normalized_per_candidate_bytes": normalized_per,
        "legacy_vector_per_candidate_bytes": legacy_vector_bytes / count if count else 0.0,
        "normalized_vector_per_candidate_bytes": (
            normalized_vector_bytes / count if count else 0.0
        ),
        "candidate_array_keys_scaled": list(_CANDIDATE_ARRAY_KEYS),
        "shared_provenance_store_bytes": store_bytes,
        "compression_ratio": legacy_bytes / normalized_bytes if normalized_bytes else None,
        "projected_candidate_count": projection_count,
        "projected_legacy_expanded_bytes": projected_legacy,
        "projected_full_snapshot_bytes": projected_normalized,
        "projected_full_snapshot_gib": projected_normalized / 1024**3,
        "projection_method": (
            "fixed normalized non-vector envelope + measured normalized vector bytes/candidate + "
            "linear upper-bound shared-store growth"
        ),
    }


def measure_feature_vector_sizes(
    vectors: Iterable[FeatureVector | Mapping[str, Any]],
    *,
    projected_candidate_count: int | None = None,
) -> dict[str, Any]:
    """Build a shared-store size report for a vector probe."""

    materialized = list(vectors)
    legacy = {"vectors": [_payload(vector, method="as_dict") for vector in materialized]}
    normalized = normalize_feature_vectors(materialized)
    result = size_comparison(
        legacy,
        normalized,
        projected_candidate_count=projected_candidate_count,
    )
    result["shared_provenance_store_digest"] = _mapping_content_digest(
        normalized["provenance_store"]
    )
    result["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    return result


def measure_replay_artifact_sizes(
    result: Any,
    *,
    projected_candidate_count: int | None = None,
) -> dict[str, Any]:
    """Measure one bounded ReplayResult without expanding a full snapshot."""

    legacy = result.artifact_dict() if hasattr(result, "artifact_dict") else dict(result)
    normalized = normalize_replay_artifact(legacy)
    comparison = size_comparison(
        legacy,
        normalized,
        projected_candidate_count=projected_candidate_count,
    )
    comparison["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    comparison["normalized_provenance_store_digest"] = _mapping_content_digest(
        normalized.get("provenance_store", {})
    )
    return comparison


def assert_lossless_expansion(
    legacy: FeatureVector | Mapping[str, Any],
    normalized: Mapping[str, Any] | None = None,
) -> bool:
    """Assert full recursive equality after normalized expansion.

    JSON canonicalization treats Python tuples as their serialized arrays, so
    this gate compares every value rather than a selected list of fields while
    remaining valid for an artifact that has crossed a JSON read/write
    boundary.
    """

    legacy_payload = _payload(legacy, method="as_dict")
    normalized_payload = normalized or normalize_feature_vector(legacy)
    expanded = expand_normalized_vector(normalized_payload)
    if canonical_json_bytes(expanded) != canonical_json_bytes(legacy_payload):
        raise AssertionError("normalized vector expansion is not lossless")
    return True


def validate_normalized_integrity(payload: Mapping[str, Any]) -> tuple[str, ...]:
    """Check that a normalized payload has refs for every physical evidence map."""

    violations: list[str] = []
    replay = payload.get("replay") if isinstance(payload, Mapping) else None
    target = replay if isinstance(replay, Mapping) else payload
    store = target.get("provenance_store", {}) if isinstance(target, Mapping) else {}
    if not isinstance(store, Mapping):
        return ("provenance_store_not_mapping",)
    vectors = target.get("vectors", []) if isinstance(target, Mapping) else []
    if not isinstance(vectors, (list, tuple)):
        return ("vectors_not_array",)
    for position, vector in enumerate(vectors):
        if not isinstance(vector, Mapping):
            violations.append(f"vector_{position}_not_mapping")
            continue
        evidence = vector.get("evidence", {})
        if not isinstance(evidence, Mapping):
            violations.append(f"vector_{position}_evidence_not_mapping")
            continue
        for name, item in evidence.items():
            if not isinstance(item, Mapping):
                violations.append(f"vector_{position}:{name}:evidence_not_mapping")
                continue
            for field_name in _EVIDENCE_REFERENCE_FIELDS:
                ref = item.get(f"{field_name}_ref")
                if not isinstance(ref, str) or ref not in store:
                    violations.append(f"vector_{position}:{name}:missing_{field_name}_ref")
    return tuple(violations)


def write_json_artifact(path: str | Path, payload: Any) -> Path:
    """Atomically write deterministic JSON for normalized artifact callers."""

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            prefix=f".{destination.name}.",
            suffix=".tmp",
            dir=destination.parent,
            delete=False,
        ) as temporary:
            temporary_path = Path(temporary.name)
            temporary.write(serialized_json_bytes(payload))
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_path, destination)
    except BaseException:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
        raise
    return destination


def write_normalized_snapshot_with_streamed_vectors(
    path: str | Path,
    snapshot: Mapping[str, Any],
    spool_path: str | Path,
    provenance_store: Mapping[str, Any] | Iterable[tuple[str, Any]],
    *,
    scores: Iterable[Any] | None = None,
    canonical_spool: bool = False,
    gzip_level: int | None = None,
    resource_probe: ResourceProbe | None = None,
    probe_interval_bytes: int = FINALIZATION_PROBE_INTERVAL_BYTES,
) -> Path:
    """Write vectors, scores, and provenance without a full envelope copy.

    The caller supplies a lightweight snapshot envelope. ``scores`` enables
    one-pass score serialization; omitting it preserves the compatibility path
    for small envelopes that already contain their score array.
    ``canonical_spool`` is reserved for the private vector spool produced from
    a successful canonical ``json.dumps`` call. ``gzip_level`` enables
    deterministic whole-stream compression (mtime=0, no original filename).
    """

    if probe_interval_bytes <= 0:
        raise ValueError("probe_interval_bytes must be positive")
    # Only these two top-level dictionaries are copied. Nested caller objects
    # are never mutated, deep-copied, or JSON-normalized as one large tree.
    payload = dict(snapshot)
    replay_source = payload.get("replay")
    if not isinstance(replay_source, Mapping) or "vectors" not in replay_source:
        raise ValueError("streamed snapshot payload is missing replay.vectors")
    replay = dict(replay_source)
    payload["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    replay["artifact_layout_version"] = NORMALIZED_ARTIFACT_LAYOUT_VERSION
    markers: dict[str, str] = {
        "vectors": "__ASHARE_NORMALIZED_VECTOR_STREAM__",
        "provenance_store": "__ASHARE_NORMALIZED_STORE_STREAM__",
    }
    replay["vectors"] = markers["vectors"]
    replay["provenance_store"] = markers["provenance_store"]
    if scores is not None:
        markers["scores"] = "__ASHARE_NORMALIZED_SCORE_STREAM__"
        replay["scores"] = markers["scores"]
    payload["replay"] = replay

    # This encoded template is intentionally only the lightweight envelope;
    # vectors, scores, and the CAS are represented by short marker strings.
    encoded = json.dumps(
        _json_safe(payload),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
        allow_nan=False,
    )
    marker_positions: list[tuple[int, str, str]] = []
    for stream_name, marker in markers.items():
        marker_text = json.dumps(marker, ensure_ascii=False)
        if encoded.count(marker_text) != 1:
            raise ValueError(f"normalized {stream_name} stream marker is not unique")
        marker_positions.append((encoded.find(marker_text), stream_name, marker_text))
    marker_positions.sort()

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    if resource_probe is not None:
        resource_probe("artifact_writer_start")
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            prefix=f".{destination.name}.",
            suffix=".tmp",
            dir=destination.parent,
            delete=False,
        ) as raw_temporary:
            temporary_path = Path(raw_temporary.name)
            compressed = (
                gzip.GzipFile(
                    filename="",
                    mode="wb",
                    compresslevel=gzip_level,
                    fileobj=raw_temporary,
                    mtime=0,
                )
                if gzip_level is not None
                else raw_temporary
            )
            temporary = io.TextIOWrapper(compressed, encoding="utf-8", newline="")
            bytes_since_probe = 0

            def write_text(text: str, phase: str) -> None:
                nonlocal bytes_since_probe
                temporary.write(text)
                if resource_probe is None:
                    return
                bytes_since_probe += len(text.encode("utf-8"))
                if bytes_since_probe >= probe_interval_bytes:
                    resource_probe(f"{phase}_interval")
                    bytes_since_probe = 0

            def write_vectors() -> None:
                if resource_probe is not None:
                    resource_probe("artifact_vector_stream_start")
                write_text("[", "artifact_vector_stream")
                first = True
                with Path(spool_path).open("r", encoding="utf-8") as spool:
                    for line in spool:
                        record = line.strip()
                        if not record:
                            continue
                        if canonical_spool:
                            if not record.startswith("{") or not record.endswith("}"):
                                raise ValueError(
                                    "canonical normalized vector spool is invalid"
                                )
                            encoded_record = record
                        else:
                            decoded = json.loads(record)
                            if not isinstance(decoded, Mapping):
                                raise ValueError(
                                    "normalized vector spool contains a non-object"
                                )
                            encoded_record = json.dumps(
                                _json_safe(decoded),
                                ensure_ascii=False,
                                sort_keys=True,
                                separators=(",", ":"),
                                allow_nan=False,
                            )
                        if not first:
                            write_text(",", "artifact_vector_stream")
                        write_text("\n", "artifact_vector_stream")
                        write_text(encoded_record, "artifact_vector_stream")
                        first = False
                write_text("\n]", "artifact_vector_stream")
                if resource_probe is not None:
                    resource_probe("artifact_vector_stream_complete")

            def write_scores() -> None:
                assert scores is not None
                if resource_probe is not None:
                    resource_probe("artifact_score_stream_start")
                write_text("[", "artifact_score_stream")
                for index, score in enumerate(scores):
                    candidate = getattr(score, "as_dict", None)
                    score_payload = candidate() if callable(candidate) else score
                    if not isinstance(score_payload, Mapping):
                        raise TypeError("streamed score must be a mapping or expose as_dict()")
                    encoded_score = json.dumps(
                        _json_safe(score_payload),
                        ensure_ascii=False,
                        sort_keys=True,
                        separators=(",", ":"),
                        allow_nan=False,
                    )
                    if index:
                        write_text(",", "artifact_score_stream")
                    write_text("\n", "artifact_score_stream")
                    write_text(encoded_score, "artifact_score_stream")
                write_text("\n]", "artifact_score_stream")
                if resource_probe is not None:
                    resource_probe("artifact_score_stream_complete")

            def write_store() -> None:
                if resource_probe is not None:
                    resource_probe("artifact_store_stream_start")
                write_text("{", "artifact_store_stream")
                entries: Iterable[tuple[str, Any]]
                if isinstance(provenance_store, Mapping):
                    entries = (
                        (str(ref), provenance_store[ref])
                        for ref in sorted(provenance_store, key=str)
                    )
                else:
                    entries = provenance_store
                for index, (ref, value) in enumerate(entries):
                    if index:
                        write_text(",", "artifact_store_stream")
                    write_text("\n  ", "artifact_store_stream")
                    write_text(
                        json.dumps(str(ref), ensure_ascii=False),
                        "artifact_store_stream",
                    )
                    write_text(": ", "artifact_store_stream")
                    if isinstance(value, bytes):
                        encoded_value = (
                            json.dumps(
                                _compressed_wrapper(value),
                                ensure_ascii=False,
                                sort_keys=True,
                                allow_nan=False,
                            )
                            if _is_compressed_bytes(value)
                            else value.decode("utf-8")
                        )
                    else:
                        encoded_value = json.dumps(
                            _json_safe(value),
                            ensure_ascii=False,
                            indent=2,
                            sort_keys=True,
                            allow_nan=False,
                        )
                    write_text(encoded_value, "artifact_store_stream")
                write_text("\n}", "artifact_store_stream")
                if resource_probe is not None:
                    resource_probe("artifact_store_stream_complete")

            stream_writers: dict[str, Callable[[], None]] = {
                "vectors": write_vectors,
                "provenance_store": write_store,
                "scores": write_scores,
            }
            cursor = 0
            for position, stream_name, marker_text in marker_positions:
                write_text(encoded[cursor:position], "artifact_envelope")
                stream_writers[stream_name]()
                cursor = position + len(marker_text)
            write_text(encoded[cursor:], "artifact_envelope")
            write_text("\n", "artifact_envelope")
            temporary.flush()
            if gzip_level is not None:
                temporary.detach().close()
            else:
                temporary.detach()
            raw_temporary.flush()
            os.fsync(raw_temporary.fileno())
            if resource_probe is not None:
                # This probe precedes atomic promotion. A raised hard gate
                # leaves only the temporary file, which the handler removes.
                resource_probe("artifact_writer_complete")
        os.replace(temporary_path, destination)
    except BaseException:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
        raise
    return destination


__all__ = [
    "NORMALIZED_ARTIFACT_LAYOUT_VERSION",
    "ARTIFACT_LAYOUT_VERSION",
    "PIT_REPLAY_ARTIFACT_LAYOUT_VERSION",
    "DIGEST_CONTRACT_VERSION",
    "FINALIZATION_PROBE_INTERVAL_BYTES",
    "ContentAddressedStore",
    "ChunkedContentAddressedStore",
    "canonical_json",
    "canonical_json_bytes",
    "content_digest",
    "content_ref",
    "serialized_json_bytes",
    "normalize_feature_vector",
    "normalize_feature_vectors",
    "normalize_replay_artifact",
    "normalize_snapshot_payload",
    "normalize_artifact",
    "expand_normalized_vector",
    "expand_normalized_replay_artifact",
    "expand_normalized_snapshot",
    "feature_vector_from_payload",
    "semantic_payload",
    "semantic_digest",
    "semantic_sequence_digest",
    "deterministic_replay_digests",
    "attribute_feature_vector_size",
    "audit_feature_vectors",
    "size_comparison",
    "measure_feature_vector_sizes",
    "measure_replay_artifact_sizes",
    "assert_lossless_expansion",
    "validate_normalized_integrity",
    "write_json_artifact",
    "write_normalized_snapshot_with_streamed_vectors",
]
